{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Federated Learning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "2024-11-30 04:55:35,234\tINFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n"
     ]
    }
   ],
   "source": [
    "import logging\n",
    "import shutil\n",
    "from collections import OrderedDict\n",
    "from pathlib import Path\n",
    "from typing import Dict, Optional, Tuple\n",
    "import wandb\n",
    "\n",
    "import lightning as L\n",
    "import matplotlib.pyplot as plt\n",
    "import torch\n",
    "from datasets.utils.logging import disable_progress_bar\n",
    "from flwr.client import Client, ClientApp, NumPyClient\n",
    "from flwr.common import Context, NDArrays, Scalar, ndarrays_to_parameters\n",
    "from flwr.server import ServerApp, ServerAppComponents, ServerConfig\n",
    "from flwr.server.strategy import FedAvg, FedProx\n",
    "from flwr.simulation import run_simulation\n",
    "from flwr_datasets.visualization import plot_label_distributions\n",
    "from lightning.pytorch.callbacks import (EarlyStopping, ModelCheckpoint,\n",
    "                                         TQDMProgressBar)\n",
    "from lightning.pytorch.loggers import WandbLogger\n",
    "from torch.utils.data import DataLoader\n",
    "\n",
    "from dataset_utils import Cinc2017DataModuleFL\n",
    "from model import DenseNet1dModule, DenseNet1dModuleFL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# disable unnecessary logging on the server side\n",
    "logging.getLogger(\"lightning.pytorch.utilities.rank_zero\").disabled = True\n",
    "logging.getLogger(\"lightning.pytorch.accelerators.cuda\").disabled = True\n",
    "disable_progress_bar()\n",
    "\n",
    "# remove old client log files\n",
    "shutil.rmtree(Path(\"logs/federated_client\"), ignore_errors=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "NUM_CLIENTS = 5\n",
    "NUM_ROUNDS = 20\n",
    "MAX_EPOCHS = 10\n",
    "BATCH_SIZE = 64\n",
    "NON_IID = True\n",
    "PROXIMAL_MU = 0"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Logging"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33mdevilhyt\u001b[0m. Use \u001b[1m`wandb login --relogin`\u001b[0m to force relogin\n",
      "/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/wandb/sdk/lib/ipython.py:84: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython.display\n",
      "  from IPython.core.display import HTML, display  # type: ignore\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "Tracking run with wandb version 0.18.7"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Run data is saved locally in <code>wandb_logs/wandb/run-20241130_045536-d6zpnl4h</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Syncing run <strong><a href='https://wandb.ai/devilhyt/ecg-federated/runs/d6zpnl4h' target=\"_blank\">ecg-federated</a></strong> to <a href='https://wandb.ai/devilhyt/ecg-federated' target=\"_blank\">Weights & Biases</a> (<a href='https://wandb.me/developer-guide' target=\"_blank\">docs</a>)<br/>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View project at <a href='https://wandb.ai/devilhyt/ecg-federated' target=\"_blank\">https://wandb.ai/devilhyt/ecg-federated</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View run at <a href='https://wandb.ai/devilhyt/ecg-federated/runs/d6zpnl4h' target=\"_blank\">https://wandb.ai/devilhyt/ecg-federated/runs/d6zpnl4h</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<button onClick=\"this.nextSibling.style.display='block';this.style.display='none';\">Display W&B run</button><iframe src='https://wandb.ai/devilhyt/ecg-federated/runs/d6zpnl4h?jupyter=true' style='border:none;width:100%;height:420px;display:none;'></iframe>"
      ],
      "text/plain": [
       "<wandb.sdk.wandb_run.Run at 0x74f026ed38d0>"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "wandb.init(\n",
    "    project=\"ecg-federated\",\n",
    "    name=\"ecg-federated\",\n",
    "    dir=\"wandb_logs\",\n",
    "    config={\n",
    "        \"NUM_CLIENTS\": NUM_CLIENTS,\n",
    "        \"NUM_ROUNDS\": NUM_ROUNDS,\n",
    "        \"MAX_EPOCHS\": MAX_EPOCHS,\n",
    "        \"BATCH_SIZE\": BATCH_SIZE,\n",
    "        \"NON_IID\": NON_IID,\n",
    "        \"PROXIMAL_MU\": PROXIMAL_MU,\n",
    "    },\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "dm = Cinc2017DataModuleFL(batch_size=BATCH_SIZE, num_partitions=NUM_CLIENTS)\n",
    "dm.setup(\"client\", NON_IID, 0.5)\n",
    "\n",
    "# dataloaders for server side evaluation\n",
    "dm.setup(\"train_eval\")\n",
    "train_loader = dm.train_eval_dataloader()\n",
    "dm.setup(\"validate\")\n",
    "valid_loader = dm.val_dataloader()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Data Distribution For Each Client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAqMAAAHHCAYAAACLElG5AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjkuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8hTgPZAAAACXBIWXMAAA9hAAAPYQGoP6dpAABFaUlEQVR4nO3deVxV5d7///cGZIMDICogiYizOIcTZaZFoml3ln7LMsOc0hs8R+mkeW5TMY1GM3Ogzimx0lNWah4tySG0DCe6cUo5VpieowypgCPj+v3hj323BRWZFsrr+Xjsx8O91rWv9Vmsrby91lrXshiGYQgAAAAwgYPZBQAAAKDmIowCAADANIRRAAAAmIYwCgAAANMQRgEAAGAawigAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAI13KhRo9SsWbNStZ09e7YsFkvlFlQF+vbtqw4dOlRon82aNdOoUaMqtM/Sio2NlcVi0bFjxyp9W1d/X44dOyaLxaI33nij0rct3T7fQQD/hzCKGq3ol3jRy8XFRa1bt1ZERITS0tIqfftFv1iLXrVr11ZgYKBmzJih7OzsCtvOyZMnNXv2bCUlJd2w7cWLFzV79mzFx8dX2PYrgsViUUREhNllVLr4+Hi774TVapW3t7f69u2rl19+WRkZGRWynep6nKXqXRuAikcYBSTNmTNHH330kRYtWqS77rpLS5cuVXBwsC5evFgl21+6dKk++ugjzZ8/X23bttW8efM0YMAAGYZRIf2fPHlSUVFRJYbRv/3tb0pOTra9v3jxoqKiokoMAjNmzNClS5cqpCZc35/+9Cd99NFHeu+99/T888/L09NTs2bNUrt27bR161a7tiNHjtSlS5fk7+9f6v6vd5yv5+rvS2XgOwjULE5mFwBUBwMHDlS3bt0kSWPHjlWDBg00f/58ffnll3riiSfK1ffFixdVu3bt67YZNmyYGjZsKEmaMGGChg4dqtWrV2vnzp0KDg4u87bz8/NVWFh43Ta1atUqdX9OTk5ycuKfjapwzz33aNiwYXbL9u3bp/79+2vo0KH66aef1LhxY0mSo6OjHB0dK7WeCxcuqE6dOjf1fakMfAeB2w8jo0AJ7rvvPklSSkqKbdnHH3+soKAgubq6ytPTU8OHD9eJEyfsPld0LWJiYqL69Omj2rVr669//Wu5tp+bm6uZM2cqKChI7u7uqlOnju655x59++23dp/547V7CxYsUIsWLWS1WrVkyRJ1795dkvTMM8/YTv/GxsZKsr8G8NixY2rUqJEkKSoqytZ29uzZkkq+Xi8/P18vvfSSbXvNmjXTX//6V+Xk5Ni1a9asmQYPHqzvv/9ePXr0kIuLi5o3b64PP/zwpn8+1/Lll19q0KBB8vX1ldVqVYsWLfTSSy+poKCgxPaJiYm666675OrqqoCAAMXExBRrk5OTo1mzZqlly5ayWq3y8/PT1KlTi+3f1fLy8hQVFaVWrVrJxcVFDRo0UO/evbVp06Yy71/nzp21YMECZWZmatGiRbblJV0zunfvXoWGhqphw4a2/Rs9erSkGx/nUaNGqW7duvrll1/04IMPql69ehoxYoRt3bWuMX7rrbfk7+8vV1dX3XvvvTp48KDd+r59+6pv377FPnc7fQcB3Dz+ewmU4JdffpEkNWjQQJI0b948vfjii3rsscc0duxYZWRk6J133lGfPn30v//7v/Lw8LB99vTp0xo4cKCGDx+up556St7e3uXafnZ2tv7+97/riSee0Lhx43Tu3Dm9//77Cg0N1e7du9WlSxe7zy5btkyXL1/W+PHjZbVa9cgjj+jcuXOaOXOmxo8fr3vuuUeSdNdddxXbbqNGjbR06VJNnDhRjzzyiB599FFJUqdOna5Z69ixY7V8+XINGzZMzz33nHbt2qXo6GgdPnxYa9assWv7888/a9iwYRozZozCwsL0wQcfaNSoUQoKClL79u1v+ud0tdjYWNWtW1eRkZGqW7eutm7dqpkzZyo7O1uvv/66XduzZ8/qwQcf1GOPPaYnnnhCq1at0sSJE+Xs7GwLbYWFhfqv//ovff/99xo/frzatWunAwcO6K233tK//vUvrV279pq1zJ49W9HR0Ro7dqx69Oih7Oxs7d27Vz/++KMeeOCBMu9j0c/vm2++0bx580psk56erv79+6tRo0Z64YUX5OHhoWPHjmn16tWSSnec8/PzFRoaqt69e+uNN9644ej+hx9+qHPnzik8PFyXL1/W22+/rfvuu08HDhy4qb8Dt/p3EEAZGEANtmzZMkOSsXnzZiMjI8M4ceKE8cknnxgNGjQwXF1djX//+9/GsWPHDEdHR2PevHl2nz1w4IDh5ORkt/zee+81JBkxMTGl2v6sWbMMSUZycrKRkZFhpKSkGO+++65htVoNb29v48KFC0Z+fr6Rk5Nj97mzZ88a3t7exujRo23LUlJSDEmGm5ubkZ6ebtd+z549hiRj2bJlxWoICwsz/P39be8zMjIMScasWbOuWW+RpKQkQ5IxduxYu3Z/+ctfDEnG1q1bbcv8/f0NScb27dtty9LT0w2r1Wo899xz1/05GYZhSDLCw8Ov2+bixYvFlj377LNG7dq1jcuXL9uWFR2nN99807YsJyfH6NKli+Hl5WXk5uYahmEYH330keHg4GB89913dn3GxMQYkowdO3bY7V9YWJjtfefOnY1BgwbdcL+u9u233xqSjM8+++yabTp37mzUr1/f9r7oe5ySkmIYhmGsWbPGkGTs2bPnmn1c7ziHhYUZkowXXnihxHV//L4Ufe+K/r4U2bVrlyHJmDJlim3Zvffea9x777037LO6fgcBVA5O0wOSQkJC1KhRI/n5+Wn48OGqW7eu1qxZozvuuEOrV69WYWGhHnvsMf3++++2l4+Pj1q1alXsdLnVatUzzzxzU9tv06aNGjVqpICAAD377LNq2bKlNmzYoNq1a8vR0VHOzs6SrozUnTlzRvn5+erWrZt+/PHHYn0NHTrUdpqzsn311VeSpMjISLvlzz33nCRpw4YNdssDAwNtI7PSlVGwNm3a6Ndff62QelxdXW1/PnfunH7//Xfdc889unjxoo4cOWLX1snJSc8++6ztvbOzs5599lmlp6crMTFRkvTZZ5+pXbt2atu2rd2xL7qM4upj/0ceHh46dOiQjh49WiH79kd169bVuXPnrrttSVq/fr3y8vLKvJ2JEyeWuu2QIUN0xx132N736NFDPXv2tH1HKkt1+w4CuHmcpgckLV68WK1bt5aTk5O8vb3Vpk0bOThc+b/a0aNHZRiGWrVqVeJnr76h44477rCFx9L64osv5Obmplq1aqlJkyZq0aKF3frly5frzTff1JEjR+zCRUBAQLG+SlpWWX777Tc5ODioZcuWdst9fHzk4eGh3377zW5506ZNi/VRv359nT17tkLqOXTokGbMmKGtW7cWmxorKyvL7r2vr6/q1Kljt6x169aSrly32KtXLx09elSHDx++ZrhPT0+/Zi1z5szRww8/rNatW6tDhw4aMGCARo4ced3TzaV1/vx51atX75rr7733Xg0dOlRRUVF666231LdvXw0ZMkRPPvmkrFZrqbbh5OSkJk2alLqmkv5+tG7dWqtWrSp1H2VR3b6DAG4eYRTQlVGcorvpr1ZYWCiLxaKvv/66xDuW69ata/f+j6NzpdWnTx/b3fRX+/jjjzVq1CgNGTJEzz//vLy8vOTo6Kjo6GjbtaXl3X55lXYS8mvd8W1UwBRWmZmZuvfee+Xm5qY5c+aoRYsWcnFx0Y8//qhp06bdcFaBkhQWFqpjx46aP39+iev9/Pyu+dk+ffrol19+0ZdffqlvvvlGf//73/XWW28pJiZGY8eOvelaiuTl5elf//rXdSftt1gs+vzzz7Vz507985//VFxcnEaPHq0333xTO3fuLPadLYnVarX9h6yiWCyWEo/1tW4wu9m+S6Myv4MAyoYwCtxAixYtZBiGAgICbCNnVenzzz9X8+bNtXr1artfuLNmzSp1HzfzxJqbaevv76/CwkIdPXpU7dq1sy1PS0tTZmbmTc17WV7x8fE6ffq0Vq9erT59+tiW/3FGhD86efKkbbqiIv/6178kyXZnd4sWLbRv3z7df//9ZXrqj6enp5555hk988wzOn/+vPr06aPZs2eXK4x+/vnnunTpkkJDQ2/YtlevXurVq5fmzZunlStXasSIEfrkk080duzYCn+KUUmXI/zrX/+yu/O+fv36JZ4Ov3r08lb9DgIoG64ZBW7g0UcflaOjo6KiooqNnhiGodOnT1fq9otGcv647V27dikhIaHUfRQFrszMzBu2LbprujRtH3zwQUnSggUL7JYXjSQOGjSo1DWWV0k/p9zcXC1ZsqTE9vn5+Xr33Xft2r777rtq1KiRgoKCJEmPPfaY/vOf/+hvf/tbsc9funRJFy5cuGY9V38v6tatq5YtW95wSqjr2bdvnyZPnqz69esrPDz8mu3Onj1b7LtaNOtC0fZv5jiXxtq1a/Wf//zH9n737t3atWuXBg4caFvWokULHTlyxO4pUvv27dOOHTvs+rpVv4MAyoaRUeAGWrRooblz52r69Ok6duyYhgwZonr16iklJUVr1qzR+PHj9Ze//KXStj948GCtXr1ajzzyiAYNGqSUlBTFxMQoMDBQ58+fL/U+eHh4KCYmRvXq1VOdOnXUs2fPEq8vdXV1VWBgoD799FO1bt1anp6e6tChQ4mnhTt37qywsDC99957ttPku3fv1vLlyzVkyBD169ev3Pv/R3v37tXcuXOLLe/bt6/uuusu1a9fX2FhYfrTn/4ki8Wijz766JqnX319ffXqq6/q2LFjat26tT799FMlJSXpvffes10HPHLkSK1atUoTJkzQt99+q7vvvlsFBQU6cuSIVq1apbi4uGte3hEYGKi+ffsqKChInp6e2rt3rz7//PNSP9L0u+++0+XLl1VQUKDTp09rx44dWrdundzd3bVmzRr5+Phc87PLly/XkiVL9Mgjj6hFixY6d+6c/va3v8nNzc0W3m7mOJdGy5Yt1bt3b02cOFE5OTlasGCBGjRooKlTp9rajB49WvPnz1doaKjGjBmj9PR0xcTEqH379nbX+Fbn7yCASmDSXfxAtVA0Jc71psAp8sUXXxi9e/c26tSpY9SpU8do27atER4ebiQnJ9va3HvvvUb79u1Lvf2iaWoyMjKu2aawsNB4+eWXDX9/f8NqtRpdu3Y11q9ff80pdl5//fUS+/nyyy+NwMBAw8nJyW6ap6v7MQzD+OGHH4ygoCDD2dnZboqdq6fVMQzDyMvLM6KiooyAgACjVq1ahp+fnzF9+nS7qZQM48q0OiVNdXSt6X6uJumar5deeskwDMPYsWOH0atXL8PV1dXw9fU1pk6dasTFxRmSjG+//dZum+3btzf27t1rBAcHGy4uLoa/v7+xaNGiYtvNzc01Xn31VaN9+/aG1Wo16tevbwQFBRlRUVFGVlaW3f79cWqnuXPnGj169DA8PDwMV1dXo23btsa8efNs00ZdS9HUTkWvWrVqGY0aNTL69OljzJs3r9i0XYZRfGqnH3/80XjiiSeMpk2bGlar1fDy8jIGDx5s7N271+5z1zrOYWFhRp06dUqs73rfuzfffNPw8/MzrFarcc899xj79u0r9vmPP/7YaN68ueHs7Gx06dLFiIuLu2W+gwAqh8UwuGobAAAA5uCaUQAAAJiGMAoAAADTEEYBAABgGlPD6NKlS9WpUye5ubnJzc1NwcHB+vrrr23rL1++rPDwcDVo0EB169bV0KFDlZaWZtfH8ePHNWjQINWuXVteXl56/vnnlZ+fb9cmPj5ed955p6xWq1q2bKnY2Niq2D0AAADcgKlhtEmTJnrllVeUmJiovXv36r777tPDDz+sQ4cOSZKmTJmif/7zn/rss8+0bds2nTx5Uo8++qjt8wUFBRo0aJByc3P1ww8/aPny5YqNjdXMmTNtbVJSUjRo0CD169dPSUlJmjx5ssaOHau4uLgq318AAADYq3Z303t6eur111/XsGHD1KhRI61cuVLDhg2TJB05ckTt2rVTQkKCevXqpa+//lqDBw/WyZMn5e3tLUmKiYnRtGnTlJGRIWdnZ02bNk0bNmzQwYMHbdsYPny4MjMztXHjRlP2EQAAAFdUm0nvCwoK9Nlnn+nChQsKDg5WYmKi8vLyFBISYmvTtm1bNW3a1BZGExIS1LFjR1sQlaTQ0FBNnDhRhw4dUteuXZWQkGDXR1GbyZMnX7OWnJwcu6ekFBYW6syZM2rQoEGFP0IPAABUDsMwdO7cOfn6+srBgdtkqivTw+iBAwcUHBysy5cvq27dulqzZo0CAwOVlJQkZ2dneXh42LX39vZWamqqJCk1NdUuiBatL1p3vTbZ2dm6dOmSXF1di9UUHR2tqKioitpFAABgohMnTqhJkyZml4FrMD2MtmnTRklJScrKytLnn3+usLAwbdu2zdSapk+frsjISNv7rKwsNW3aVCdOnJCbm5uJlQEAgNLKzs6Wn5+f6tWrZ3YpuA7Tw6izs7NatmwpSQoKCtKePXv09ttv6/HHH1dubq4yMzPtRkfT0tJsz2T28fHR7t277forutv+j22uvgM/LS1Nbm5uJY6KSpLVapXVai22vOiufwAAcOvgErvqrdpdQFFYWKicnBwFBQWpVq1a2rJli21dcnKyjh8/ruDgYElScHCwDhw4oPT0dFubTZs2yc3NTYGBgbY2f+yjqE1RHwAAADCPqSOj06dP18CBA9W0aVOdO3dOK1euVHx8vOLi4uTu7q4xY8YoMjJSnp6ecnNz06RJkxQcHKxevXpJkvr376/AwECNHDlSr732mlJTUzVjxgyFh4fbRjYnTJigRYsWaerUqRo9erS2bt2qVatWacOGDWbuOgAAAGRyGE1PT9fTTz+tU6dOyd3dXZ06dVJcXJweeOABSdJbb70lBwcHDR06VDk5OQoNDdWSJUtsn3d0dNT69es1ceJEBQcHq06dOgoLC9OcOXNsbQICArRhwwZNmTJFb7/9tpo0aaK///3vCg0NrfL9BQAAgL1qN89odZSdnS13d3dlZWVxzSgAALcIfn/fGqrdNaMAAACoOQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApnEyuwCgOrJM7GV2CRXCWLrT7BIAALguRkYBAABgGsIoAAAATEMYBQAAgGkIowAAADANYRQAAACmIYwCAADANIRRAAAAmIYwCgAAANMQRgEAAGAawigAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApiGMAgAAwDSEUQAAAJiGMAoAAADTEEYBAABgGsIoAAAATEMYBQAAgGkIowAAADANYRQAAACmIYwCAADANIRRAAAAmIYwCgAAANMQRgEAAGAawigAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYxtQwGh0dre7du6tevXry8vLSkCFDlJycbNemb9++slgsdq8JEybYtTl+/LgGDRqk2rVry8vLS88//7zy8/Pt2sTHx+vOO++U1WpVy5YtFRsbW9m7BwAAgBswNYxu27ZN4eHh2rlzpzZt2qS8vDz1799fFy5csGs3btw4nTp1yvZ67bXXbOsKCgo0aNAg5ebm6ocfftDy5csVGxurmTNn2tqkpKRo0KBB6tevn5KSkjR58mSNHTtWcXFxVbavAAAAKM5iGIZhdhFFMjIy5OXlpW3btqlPnz6SroyMdunSRQsWLCjxM19//bUGDx6skydPytvbW5IUExOjadOmKSMjQ87Ozpo2bZo2bNiggwcP2j43fPhwZWZmauPGjTesKzs7W+7u7srKypKbm1v5dxTVnmViL7NLqBDG0p1mlwAApuH3962hWl0zmpWVJUny9PS0W75ixQo1bNhQHTp00PTp03Xx4kXbuoSEBHXs2NEWRCUpNDRU2dnZOnTokK1NSEiIXZ+hoaFKSEgosY6cnBxlZ2fbvQAAAFDxnMwuoEhhYaEmT56su+++Wx06dLAtf/LJJ+Xv7y9fX1/t379f06ZNU3JyslavXi1JSk1NtQuikmzvU1NTr9smOztbly5dkqurq9266OhoRUVFVfg+AgAAwF61CaPh4eE6ePCgvv/+e7vl48ePt/25Y8eOaty4se6//3798ssvatGiRaXUMn36dEVGRtreZ2dny8/Pr1K2BQAAUJNVi9P0ERERWr9+vb799ls1adLkum179uwpSfr5558lST4+PkpLS7NrU/Tex8fnum3c3NyKjYpKktVqlZubm90LAAAAFc/UMGoYhiIiIrRmzRpt3bpVAQEBN/xMUlKSJKlx48aSpODgYB04cEDp6em2Nps2bZKbm5sCAwNtbbZs2WLXz6ZNmxQcHFxBewIAAICyMDWMhoeH6+OPP9bKlStVr149paamKjU1VZcuXZIk/fLLL3rppZeUmJioY8eOad26dXr66afVp08fderUSZLUv39/BQYGauTIkdq3b5/i4uI0Y8YMhYeHy2q1SpImTJigX3/9VVOnTtWRI0e0ZMkSrVq1SlOmTDFt3wEAAGDy1E4Wi6XE5cuWLdOoUaN04sQJPfXUUzp48KAuXLggPz8/PfLII5oxY4bdqfPffvtNEydOVHx8vOrUqaOwsDC98sorcnL6v0ti4+PjNWXKFP30009q0qSJXnzxRY0aNapUdTI1RM3D1E4AcOvj9/etoVrNM1pd8WWueQijAHDr4/f3raFa3MAEAACAmokwCgAAANMQRgEAAGAawigAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApiGMAgAAwDSEUQAAAJiGMAoAAADTEEYBAABgGsIoAAAATEMYBQAAgGkIowAAADANYRQAAACmIYwCAADANIRRAAAAmIYwCgAAANMQRgEAAGAawigAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApiGMAgAAwDSEUQAAAJiGMAoAAADTEEYBAABgGsIoAAAATEMYBQAAgGkIowAAADANYRQAAACmIYwCAADANIRRAAAAmIYwCgAAANOYGkajo6PVvXt31atXT15eXhoyZIiSk5Pt2ly+fFnh4eFq0KCB6tatq6FDhyotLc2uzfHjxzVo0CDVrl1bXl5eev7555Wfn2/XJj4+XnfeeaesVqtatmyp2NjYyt49AAAA3ICpYXTbtm0KDw/Xzp07tWnTJuXl5al///66cOGCrc2UKVP0z3/+U5999pm2bdumkydP6tFHH7WtLygo0KBBg5Sbm6sffvhBy5cvV2xsrGbOnGlrk5KSokGDBqlfv35KSkrS5MmTNXbsWMXFxVXp/gIAAMCexTAMw+wiimRkZMjLy0vbtm1Tnz59lJWVpUaNGmnlypUaNmyYJOnIkSNq166dEhIS1KtXL3399dcaPHiwTp48KW9vb0lSTEyMpk2bpoyMDDk7O2vatGnasGGDDh48aNvW8OHDlZmZqY0bN96wruzsbLm7uysrK0tubm6Vs/OoViwTe5ldQoUwlu40uwQAMA2/v28N1eqa0aysLEmSp6enJCkxMVF5eXkKCQmxtWnbtq2aNm2qhIQESVJCQoI6duxoC6KSFBoaquzsbB06dMjW5o99FLUp6uNqOTk5ys7OtnsBAACg4lWbMFpYWKjJkyfr7rvvVocOHSRJqampcnZ2loeHh11bb29vpaam2tr8MYgWrS9ad7022dnZunTpUrFaoqOj5e7ubnv5+flVyD4CAADAXrUJo+Hh4Tp48KA++eQTs0vR9OnTlZWVZXudOHHC7JIAAABuS05mFyBJERERWr9+vbZv364mTZrYlvv4+Cg3N1eZmZl2o6NpaWny8fGxtdm9e7ddf0V32/+xzdV34KelpcnNzU2urq7F6rFarbJarRWybwAAALg2U0dGDcNQRESE1qxZo61btyogIMBufVBQkGrVqqUtW7bYliUnJ+v48eMKDg6WJAUHB+vAgQNKT0+3tdm0aZPc3NwUGBhoa/PHPoraFPUBAAAAc5g6MhoeHq6VK1fqyy+/VL169WzXeLq7u8vV1VXu7u4aM2aMIiMj5enpKTc3N02aNEnBwcHq1evK3c79+/dXYGCgRo4cqddee02pqamaMWOGwsPDbaObEyZM0KJFizR16lSNHj1aW7du1apVq7RhwwbT9h0AAAAmT+1ksVhKXL5s2TKNGjVK0pVJ75977jn94x//UE5OjkJDQ7VkyRLbKXhJ+u233zRx4kTFx8erTp06CgsL0yuvvCInp//L2vHx8ZoyZYp++uknNWnSRC+++KJtGzfC1BA1D1M7AcCtj9/ft4ZqNc9odcWXueYhjALArY/f37eGanM3PQAAAGoewigAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA05j6OFAAAICaxDAM5efnq6CgwOxSKpWjo6OcnJyu+bTNPyKMAgAAVIHc3FydOnVKFy9eNLuUKlG7dm01btxYzs7O121HGAUAAKhkhYWFSklJkaOjo3x9feXs7FyqUcNbkWEYys3NVUZGhlJSUtSqVSs5OFz7ylDCKAAAQCXLzc1VYWGh/Pz8VLt2bbPLqXSurq6qVauWfvvtN+Xm5srFxeWabbmBCQAAoIpcb4TwdlPafa05PxEAAABUO5ymB0pQuDTa7BIAALgpsbGxmjx5sjIzM8vVj8Vi0Zo1azRkyJAKqetGGBkFAACoJkaNGlVlIbC6IIwCAADANIRRAACAW8D8+fPVsWNH1alTR35+fvrv//5vnT9/vli7tWvXqlWrVnJxcVFoaKhOnDhht/7LL7/UnXfeKRcXFzVv3lxRUVHKz88vcZu5ubmKiIhQ48aN5eLiIn9/f0VHV+ylbIRRAACAW4CDg4MWLlyoQ4cOafny5dq6daumTp1q1+bixYuaN2+ePvzwQ+3YsUOZmZkaPny4bf13332np59+Wn/+85/1008/6d1331VsbKzmzZtX4jYXLlyodevWadWqVUpOTtaKFSvUrFmzCt0vbmACAAC4BUyePNn252bNmmnu3LmaMGGClixZYluel5enRYsWqWfPnpKk5cuXq127dtq9e7d69OihqKgovfDCCwoLC5MkNW/eXC+99JKmTp2qWbNmFdvm8ePH1apVK/Xu3VsWi0X+/v4Vvl+MjAIAANwCNm/erPvvv1933HGH6tWrp5EjR+r06dN2jxd1cnJS9+7dbe/btm0rDw8PHT58WJK0b98+zZkzR3Xr1rW9xo0bd83HlI4aNUpJSUlq06aN/vSnP+mbb76p8P0ijAIAAFRzx44d0+DBg9WpUyd98cUXSkxM1OLFiyVdua6ztM6fP6+oqCglJSXZXgcOHNDRo0dLfErSnXfeqZSUFL300ku6dOmSHnvsMQ0bNqzC9kviND0AAEC1l5iYqMLCQr355pu2JxutWrWqWLv8/Hzt3btXPXr0kCQlJycrMzNT7dq1k3QlXCYnJ6tly5al3rabm5sef/xxPf744xo2bJgGDBigM2fOyNPTswL2jDAKAABQrWRlZSkpKcluWcOGDZWXl6d33nlHDz30kHbs2KGYmJhin61Vq5YmTZqkhQsXysnJSREREerVq5ctnM6cOVODBw9W06ZNNWzYMDk4OGjfvn06ePCg5s6dW6y/+fPnq3HjxuratascHBz02WefycfHRx4eHhW2v5ymBwAAqEbi4+PVtWtXu9dHH32k+fPn69VXX1WHDh20YsWKEqdYql27tqZNm6Ynn3xSd999t+rWratPP/3Utj40NFTr16/XN998o+7du6tXr1566623rnljUr169fTaa6+pW7du6t69u44dO6avvvqq1M+dLw2LYRhGhfV2m8rOzpa7u7uysrLk5uZmdjmoAoa+NbuECmFRP7NLAADTVKff35cvX1ZKSooCAgJKvDbzdlTafWZkFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrmGQVK8A/LBLNLqBBPGslmlwAAwHUxMgoAAADTEEYBAABgGsIoAAAATEMYBQAAgGm4gQkAAMBElom9qmxbxtKdZfrciRMnNGvWLG3cuFG///67GjdurCFDhmjmzJlq0KBBuWoq08ho8+bNdfr06WLLMzMz1bx583IVBAAAgOrj119/Vbdu3XT06FH94x//0M8//6yYmBht2bJFwcHBOnPmTLn6L9PI6LFjx1RQUFBseU5Ojv7zn/+UqyAAAABUH+Hh4XJ2dtY333wjV1dXSVLTpk3VtWtXtWjRQv/zP/+jpUuXlrn/mwqj69ats/05Li5O7u7utvcFBQXasmWLmjVrVuZiAAAAUH2cOXNGcXFxmjdvni2IFvHx8dGIESP06aefasmSJbJYLGXaxk2F0SFDhkiSLBaLwsLC7NbVqlVLzZo105tvvlmmQgAAAFC9HD16VIZhqF27diWub9eunc6ePauMjAx5eXmVaRs3FUYLCwslSQEBAdqzZ48aNmxYpo0CAADg1mEYRqX1XaYbmFJSUgiiAAAAt7mWLVvKYrHo8OHDJa4/fPiw6tevr0aNGpV5G2We2mnLli3asmWL0tPTbSOmRT744IMyFwQAAIDqoUGDBnrggQe0ZMkSTZkyxe660dTUVK1YsUJPP/10ma8Xlco4MhoVFaX+/ftry5Yt+v3333X27Fm7FwAAAG4PixYtUk5OjkJDQ7V9+3adOHFCGzdu1AMPPKA77rhD8+bNK1f/ZRoZjYmJUWxsrEaOHFmujQMAAKB6a9Wqlfbu3atZs2bpscce05kzZ+Tj46MhQ4Zo1qxZ8vT0LFf/ZQqjubm5uuuuu8q1YQAAAJT9qUhVyd/fX7GxsZXSd5lO048dO1YrV66s6FoAAABQw5RpZPTy5ct67733tHnzZnXq1Em1atWyWz9//vwKKQ4AAAC3tzKF0f3796tLly6SpIMHD9qtK8/dVAAAAKhZyhRGv/3224quAwAAADVQma4ZrSjbt2/XQw89JF9fX1ksFq1du9Zu/ahRo2SxWOxeAwYMsGtz5swZjRgxQm5ubvLw8NCYMWN0/vx5uzb79+/XPffcIxcXF/n5+em1116r7F0DAABAKZRpZLRfv37XPR2/devWUvVz4cIFde7cWaNHj9ajjz5aYpsBAwZo2bJltvdWq9Vu/YgRI3Tq1Clt2rRJeXl5euaZZzR+/HjbDVbZ2dnq37+/QkJCFBMTowMHDmj06NHy8PDQ+PHjS1UnAAAAKkeZwmjR9aJF8vLylJSUpIMHDyosLKzU/QwcOFADBw68bhur1SofH58S1x0+fFgbN27Unj171K1bN0nSO++8owcffFBvvPGGfH19tWLFCuXm5uqDDz6Qs7Oz2rdvr6SkJM2fP58wCgAAYLIyhdG33nqrxOWzZ88udoq8vOLj4+Xl5aX69evrvvvu09y5c9WgQQNJUkJCgjw8PGxBVJJCQkLk4OCgXbt26ZFHHlFCQoL69OkjZ2dnW5vQ0FC9+uqrOnv2rOrXr19smzk5OcrJybG9z87OrtB9AgAAwBVlfjZ9SZ566in16NFDb7zxRoX0N2DAAD366KMKCAjQL7/8or/+9a8aOHCgEhIS5OjoqNTUVHl5edl9xsnJSZ6enkpNTZV05bmpAQEBdm28vb1t60oKo9HR0YqKiqqQfbgZlom9qnybleFWmLwXAABUDxUaRhMSEuTi4lJh/Q0fPtz2544dO6pTp05q0aKF4uPjdf/991fYdq42ffp0RUZG2t5nZ2fLz8+v0rYHAABQU5UpjF59s5FhGDp16pT27t2rF198sUIKK0nz5s3VsGFD/fzzz7r//vvl4+Oj9PR0uzb5+fm2Z6ZKko+Pj9LS0uzaFL2/1rWoVqu12I1SAAAAlcFQ1U2ZaVG/Mn82ISFBvXv31oABA7Rhw4YKq6lMUzu5u7vbvTw9PdW3b1999dVXmjVrVoUVd7V///vfOn36tBo3bixJCg4OVmZmphITE21ttm7dqsLCQvXs2dPWZvv27crLy7O12bRpk9q0aVPiKXoAAAAU9/7772vSpEnavn27Tp48WWH9lmlk9I9TLZXH+fPn9fPPP9vep6SkKCkpSZ6envL09FRUVJSGDh0qHx8f/fLLL5o6dapatmyp0NBQSVK7du00YMAAjRs3TjExMcrLy1NERISGDx8uX19fSdKTTz6pqKgojRkzRtOmTdPBgwf19ttvX/MmLAAAANg7f/68Pv30U+3du1epqamKjY3VX//61wrpu1yT3icmJurjjz/Wxx9/rP/93/+96c/v3btXXbt2VdeuXSVJkZGR6tq1q2bOnClHR0ft379f//Vf/6XWrVtrzJgxCgoK0nfffWd3Cn3FihVq27at7r//fj344IPq3bu33nvvPdt6d3d3ffPNN0pJSVFQUJCee+45zZw5k2mdAAAASmnVqlVq27at2rRpo6eeekoffPCBDMOokL7LNDKanp6u4cOHKz4+Xh4eHpKkzMxM9evXT5988okaNWpUqn769u173R2Ji4u7YR+enp62Ce6vpVOnTvruu+9KVRMAAADsvf/++3rqqackXZntKCsrS9u2bVPfvn3L3XeZRkYnTZqkc+fO6dChQzpz5ozOnDmjgwcPKjs7W3/605/KXRQAAACqh+TkZO3evVtPPPGEpCvTaD7++ON6//33K6T/Mo2Mbty4UZs3b1a7du1sywIDA7V48WL179+/QgoDAACA+d5//33l5+fb7seRrsykZLVatWjRIrm7u5er/zKNjBYWFqpWrVrFlteqVUuFhYXlKggAAADVQ35+vj788EO9+eabSkpKsr327dsnX19f/eMf/yj3NsoURu+77z79+c9/trut/z//+Y+mTJlSqZPRAwAAoOqsX79eZ8+e1ZgxY9ShQwe719ChQyvkVH2ZwuiiRYuUnZ2tZs2aqUWLFmrRooUCAgKUnZ2td955p9xFAQAAwHzvv/++QkJCSjwVP3ToUO3du1f79+8v1zbKdM2on5+ffvzxR23evFlHjhyRdGXOz5CQkHIVAwAAUNOU56lIle2f//znNdf16NGjQqZ3uqmR0a1btyowMFDZ2dmyWCx64IEHNGnSJE2aNEndu3dX+/btmUIJAAAApXZTYXTBggUaN26c3Nzciq1zd3fXs88+q/nz51dYcQAAALi93VQY3bdvnwYMGHDN9f3797d7TjwAAABwPTcVRtPS0kqc0qmIk5OTMjIyyl0UAAAAaoabCqN33HGHDh48eM31+/fvV+PGjctdFAAAAGqGmwqjDz74oF588UVdvny52LpLly5p1qxZGjx4cIUVBwAAgNvbTU3tNGPGDK1evVqtW7dWRESE2rRpI0k6cuSIFi9erIKCAv3P//xPpRQKAACA289NhVFvb2/98MMPmjhxoqZPn26bW8pisSg0NFSLFy+Wt7d3pRQKAACA289NT3rv7++vr776SmfPntXPP/8swzDUqlUr1a9fvzLqAwAAwG2sTE9gkqT69eure/fuFVkLAAAAapgyh1EAAACU30pLmyrb1pNG8k1/ZtSoUVq+fLmio6P1wgsv2JavXbtWjzzySLkfCXpTd9MDAACg5nFxcdGrr76qs2fPVnjfhFEAAABcV0hIiHx8fBQdHV3hfRNGAQAAcF2Ojo56+eWX9c477+jf//53hfZNGAUAAMANPfLII+rSpYtmzZpVof0SRgEAAFAqr776qpYvX67Dhw9XWJ+EUQAAAJRKnz59FBoaqunTp1dYn0ztBAAAgFJ75ZVX1KVLF9tj4cuLkVEAAACUWseOHTVixAgtXLiwQvojjAIAAOCmzJkzR4WFhRXSF6fpAQAATFSWpyJVpdjY2GLLmjVrppycnArpnzAKACg1y8ReZpdQbsbSnWaXAOAPOE0PAAAA0zAyWo0ULq34R2wBAABUZ4RRAECp8Z9mABWN0/QAAAAwDWEUAACgilTUdEi3gtLuK6fpAQAAKpmzs7McHBx08uRJNWrUSM7OzrJYLGaXVSkMw1Bubq4yMjLk4OAgZ2fn67YnjFYj/7BMMLuEClHd50sDAKCqOTg4KCAgQKdOndLJkyfNLqdK1K5dW02bNpWDw/VPxBNGAQAAqoCzs7OaNm2q/Px8FRQUmF1OpXJ0dJSTk1OpRn8JowAAAFXEYrGoVq1aqlWrltmlVBvcwAQAAADTEEYBAABgGsIoAAAATEMYBQAAgGm4gQkAUGq3wxR0TD8HVC+MjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApjE1jG7fvl0PPfSQfH19ZbFYtHbtWrv1hmFo5syZaty4sVxdXRUSEqKjR4/atTlz5oxGjBghNzc3eXh4aMyYMTp//rxdm/379+uee+6Ri4uL/Pz89Nprr1X2rgEAAKAUTA2jFy5cUOfOnbV48eIS17/22mtauHChYmJitGvXLtWpU0ehoaG6fPmyrc2IESN06NAhbdq0SevXr9f27ds1fvx42/rs7Gz1799f/v7+SkxM1Ouvv67Zs2frvffeq/T9AwAAwPWZ+jjQgQMHauDAgSWuMwxDCxYs0IwZM/Twww9Lkj788EN5e3tr7dq1Gj58uA4fPqyNGzdqz5496tatmyTpnXfe0YMPPqg33nhDvr6+WrFihXJzc/XBBx/I2dlZ7du3V1JSkubPn28XWgEAAFD1qu01oykpKUpNTVVISIhtmbu7u3r27KmEhARJUkJCgjw8PGxBVJJCQkLk4OCgXbt22dr06dNHzs7OtjahoaFKTk7W2bNnq2hvAAAAUBJTR0avJzU1VZLk7e1tt9zb29u2LjU1VV5eXnbrnZyc5OnpadcmICCgWB9F6+rXr19s2zk5OcrJybG9z87OLufeAAAAoCTVdmTUTNHR0XJ3d7e9/Pz8zC4JAADgtlRtw6iPj48kKS0tzW55WlqabZ2Pj4/S09Pt1ufn5+vMmTN2bUrq44/buNr06dOVlZVle504caL8OwQAAIBiqm0YDQgIkI+Pj7Zs2WJblp2drV27dik4OFiSFBwcrMzMTCUmJtrabN26VYWFherZs6etzfbt25WXl2drs2nTJrVp06bEU/SSZLVa5ebmZvcCAABAxTM1jJ4/f15JSUlKSkqSdOWmpaSkJB0/flwWi0WTJ0/W3LlztW7dOh04cEBPP/20fH19NWTIEElSu3btNGDAAI0bN067d+/Wjh07FBERoeHDh8vX11eS9OSTT8rZ2VljxozRoUOH9Omnn+rtt99WZGSkSXsNAACAIqbewLR3717169fP9r4oIIaFhSk2NlZTp07VhQsXNH78eGVmZqp3797auHGjXFxcbJ9ZsWKFIiIidP/998vBwUFDhw7VwoULbevd3d31zTffKDw8XEFBQWrYsKFmzpzJtE4AAADVgMUwDMPsIqq77Oxsubu7Kysrq1JP2a+0tKm0vqvSk0ay2SWUG8cCKNnt8HeDvxc1R1X9/kb5VNtrRgEAAHD7I4wCAADANIRRAAAAmIYwCgAAANMQRgEAAGAawigAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApiGMAgAAwDSEUQAAAJiGMAoAAADTEEYBAABgGsIoAAAATEMYBQAAgGkIowAAADANYRQAAACmIYwCAADANIRRAAAAmIYwCgAAANMQRgEAAGAawigAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApiGMAgAAwDROZhcAAABunmViL7NLqBDG0p1mlwCTMTIKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApiGMAgAAwDSEUQAAAJimWofR2bNny2Kx2L3atm1rW3/58mWFh4erQYMGqlu3roYOHaq0tDS7Po4fP65Bgwapdu3a8vLy0vPPP6/8/Pyq3hUAAACUoNo/gal9+/bavHmz7b2T0/+VPGXKFG3YsEGfffaZ3N3dFRERoUcffVQ7duyQJBUUFGjQoEHy8fHRDz/8oFOnTunpp59WrVq19PLLL1f5vgAAAMBetQ+jTk5O8vHxKbY8KytL77//vlauXKn77rtPkrRs2TK1a9dOO3fuVK9evfTNN9/op59+0ubNm+Xt7a0uXbropZde0rRp0zR79mw5OztX9e4AAADgD6r1aXpJOnr0qHx9fdW8eXONGDFCx48flyQlJiYqLy9PISEhtrZt27ZV06ZNlZCQIElKSEhQx44d5e3tbWsTGhqq7OxsHTp06JrbzMnJUXZ2tt0LAAAAFa9ah9GePXsqNjZWGzdu1NKlS5WSkqJ77rlH586dU2pqqpydneXh4WH3GW9vb6WmpkqSUlNT7YJo0fqiddcSHR0td3d328vPz69idwwAAACSqvlp+oEDB9r+3KlTJ/Xs2VP+/v5atWqVXF1dK22706dPV2RkpO19dnY2gRQAAKASVOuR0at5eHiodevW+vnnn+Xj46Pc3FxlZmbatUlLS7NdY+rj41Ps7vqi9yVdh1rEarXKzc3N7gUAAICKd0uF0fPnz+uXX35R48aNFRQUpFq1amnLli229cnJyTp+/LiCg4MlScHBwTpw4IDS09NtbTZt2iQ3NzcFBgZWef0AAACwV61P0//lL3/RQw89JH9/f508eVKzZs2So6OjnnjiCbm7u2vMmDGKjIyUp6en3NzcNGnSJAUHB6tXr16SpP79+yswMFAjR47Ua6+9ptTUVM2YMUPh4eGyWq0m7x0AAACqdRj997//rSeeeEKnT59Wo0aN1Lt3b+3cuVONGjWSJL311ltycHDQ0KFDlZOTo9DQUC1ZssT2eUdHR61fv14TJ05UcHCw6tSpo7CwMM2ZM8esXQIAAMAfVOsw+sknn1x3vYuLixYvXqzFixdfs42/v7+++uqrii4NAAAAFeCWumYUAAAAtxfCKAAAAExDGAUAAIBpCKMAAAAwTbW+gQkAJMkysZfZJZSbsXSn2SUAQLXEyCgAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpeBwoAAC3oMKl0WaXAFQIRkYBAABgGsIoAAAATEMYBQAAgGkIowAAADANYRQAAACmIYwCAADANIRRAAAAmIYwCgAAANMQRgEAAGAawigAAABMQxgFAACAaQijAAAAMA1hFAAAAKYhjAIAAMA0hFEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApiGMAgAAwDSEUQAAAJiGMAoAAADTEEYBAABgGsIoAAAATEMYBQAAgGmczC4AAG6kcGm02SUAACoJI6MAAAAwDWEUAAAApiGMAgAAwDSEUQAAAJiGG5gAALgF/cMywewSKsSTRrLZJcBkjIwCAADANDVqZHTx4sV6/fXXlZqaqs6dO+udd95Rjx49zC4LwA3cDiNAjP4AQMlqzMjop59+qsjISM2aNUs//vijOnfurNDQUKWnp5tdGgAAQI1VY8Lo/PnzNW7cOD3zzDMKDAxUTEyMateurQ8++MDs0gAAAGqsGhFGc3NzlZiYqJCQENsyBwcHhYSEKCEhwcTKAAAAarYacc3o77//roKCAnl7e9st9/b21pEjR4q1z8nJUU5Oju19VlaWJCk7O7tS67yogkrtv6pU9s+pKnAsqpfb4XhwLKoPjkX1UpnHo6hvwzAqbRsovxoRRm9WdHS0oqKiii338/MzoZpbzzh3d7NLwP+PY1F9cCyqD45F9VIVx+PcuXNy57hXWzUijDZs2FCOjo5KS0uzW56WliYfH59i7adPn67IyEjb+8LCQp05c0YNGjSQxWKp9HorS3Z2tvz8/HTixAm5ubmZXU6NxrGoPjgW1QvHo/q4HY6FYRg6d+6cfH19zS4F11Ejwqizs7OCgoK0ZcsWDRkyRNKVgLllyxZFREQUa2+1WmW1Wu2WeXh4VEGlVcPNze2W/YfldsOxqD44FtULx6P6uNWPBSOi1V+NCKOSFBkZqbCwMHXr1k09evTQggULdOHCBT3zzDNmlwYAAFBj1Zgw+vjjjysjI0MzZ85UamqqunTpoo0bNxa7qQkAAABVp8aEUUmKiIgo8bR8TWG1WjVr1qxilyCg6nEsqg+ORfXC8ag+OBaoKhaD+Q4AAABgkhox6T0AAACqJ8IoAAAATEMYBQAAgGkIowAAADANYbQGWbx4sZo1ayYXFxf17NlTu3fvNrukGmf79u166KGH5OvrK4vForVr15pdUo0VHR2t7t27q169evLy8tKQIUOUnJxsdlk10tKlS9WpUyfb5OrBwcH6+uuvzS4Lkl555RVZLBZNnjzZ7FJwGyOM1hCffvqpIiMjNWvWLP3444/q3LmzQkNDlZ6ebnZpNcqFCxfUuXNnLV682OxSarxt27YpPDxcO3fu1KZNm5SXl6f+/fvrwoULZpdW4zRp0kSvvPKKEhMTtXfvXt133316+OGHdejQIbNLq9H27Nmjd999V506dTK7FNzmmNqphujZs6e6d++uRYsWSbryOFQ/Pz9NmjRJL7zwgsnV1UwWi0Vr1qyxPaIW5srIyJCXl5e2bdumPn36mF1Ojefp6anXX39dY8aMMbuUGun8+fO68847tWTJEs2dO1ddunTRggULzC4LtylGRmuA3NxcJSYmKiQkxLbMwcFBISEhSkhIMLEyoPrIysqSdCUEwTwFBQX65JNPdOHCBQUHB5tdTo0VHh6uQYMG2f3eACpLjXoCU031+++/q6CgoNijT729vXXkyBGTqgKqj8LCQk2ePFl33323OnToYHY5NdKBAwcUHBysy5cvq27dulqzZo0CAwPNLqtG+uSTT/Tjjz9qz549ZpeCGoIwCqDGCw8P18GDB/X999+bXUqN1aZNGyUlJSkrK0uff/65wsLCtG3bNgJpFTtx4oT+/Oc/a9OmTXJxcTG7HNQQhNEaoGHDhnJ0dFRaWprd8rS0NPn4+JhUFVA9REREaP369dq+fbuaNGlidjk1lrOzs1q2bClJCgoK0p49e/T222/r3XffNbmymiUxMVHp6em68847bcsKCgq0fft2LVq0SDk5OXJ0dDSxQtyOuGa0BnB2dlZQUJC2bNliW1ZYWKgtW7ZwTRZqLMMwFBERoTVr1mjr1q0KCAgwuyT8QWFhoXJycswuo8a5//77deDAASUlJdle3bp104gRI5SUlEQQRaVgZLSGiIyMVFhYmLp166YePXpowYIFunDhgp555hmzS6tRzp8/r59//tn2PiUlRUlJSfL09FTTpk1NrKzmCQ8P18qVK/Xll1+qXr16Sk1NlSS5u7vL1dXV5OpqlunTp2vgwIFq2rSpzp07p5UrVyo+Pl5xcXFml1bj1KtXr9h103Xq1FGDBg24nhqVhjBaQzz++OPKyMjQzJkzlZqaqi5dumjjxo3FbmpC5dq7d6/69etnex8ZGSlJCgsLU2xsrElV1UxLly6VJPXt29du+bJlyzRq1KiqL6gGS09P19NPP61Tp07J3d1dnTp1UlxcnB544AGzSwNQBZhnFAAAAKbhmlEAAACYhjAKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApiGMArhtHTt2TBaLRUlJSddt17dvX02ePLlKagIA2COMAqhSo0aNksVikcVikbOzs1q2bKk5c+YoPz+/3P0OGTLEbpmfn59OnTple4xhfHy8LBaLMjMz7dqtXr1aL730Urm2fyNXB+Oi90WvevXqqX379goPD9fRo0crtRYAqE4IowCq3IABA3Tq1CkdPXpUzz33nGbPnq3XX3+9TH0VFBSosLCwxHWOjo7y8fGRk9P1n3zs6empevXqlWn75bV582adOnVK+/bt08svv6zDhw+rc+fO2rJliyn1AEBVI4wCqHJWq1U+Pj7y9/fXxIkTFRISonXr1kmS5s+fr44dO6pOnTry8/PTf//3f+v8+fO2z8bGxsrDw0Pr1q1TYGCgrFarRo8ereXLl+vLL7+0jTTGx8fbjUYeO3ZM/fr1kyTVr19fFovF9gz6q0/Tnz17Vk8//bTq16+v2rVra+DAgXajlUU1xMXFqV27dqpbt64tYN+sBg0ayMfHR82bN9fDDz+szZs3q2fPnhozZowKCgrK8NMFgFsLYRSA6VxdXZWbmytJcnBw0MKFC3Xo0CEtX75cW7du1dSpU+3aX7x4Ua+++qr+/ve/69ChQ1q4cKEee+wxWyA8deqU7rrrLrvP+Pn56YsvvpAkJScn69SpU3r77bdLrGfUqFHau3ev1q1bp4SEBBmGoQcffFB5eXl2Nbzxxhv66KOPtH37dh0/flx/+ctfyv2zcHBw0J///Gf99ttvSkxMLHd/AFDdXf/cFQBUIsMwtGXLFsXFxWnSpEmSZDdC2axZM82dO1cTJkzQkiVLbMvz8vK0ZMkSde7c2bbM1dVVOTk58vHxKXFbjo6O8vT0lCR5eXnJw8OjxHZHjx7VunXrtGPHDlugXbFihfz8/LR27Vr9v//3/2w1xMTEqEWLFpKkiIgIzZkzp2w/iKu0bdtW0pXrSnv06FEhfQJAdUUYBVDl1q9fr7p16yovL0+FhYV68sknNXv2bElXrqGMjo7WkSNHlJ2drfz8fF2+fFkXL15U7dq1JUnOzs7q1KlTpdR2+PBhOTk5qWfPnrZlDRo0UJs2bXT48GHbstq1a9uCqCQ1btxY6enpFVKDYRiSJIvFUiH9AUB1xml6AFWuX79+SkpK0tGjR3Xp0iUtX75cderU0bFjxzR48GB16tRJX3zxhRITE7V48WJJsp3Gl66Mgpod1GrVqmX33mKx2EJkeRWF3oCAgArpDwCqM0ZGAVS5OnXqqGXLlsWWJyYmqrCwUG+++aYcHK78X3nVqlWl6tPZ2fmGN/w4OztL0nXbtWvXTvn5+dq1a5ftNP3p06eVnJyswMDAUtVSHoWFhVq4cKECAgLUtWvXSt8eAJiNkVEA1UbLli2Vl5end955R7/++qs++ugjxcTElOqzzZo10/79+5WcnKzff//d7majIv7+/rJYLFq/fr0yMjLs7tIv0qpVKz388MMaN26cvv/+e+3bt09PPfWU7rjjDj388MPl3sernT59Wqmpqfr111+1bt06hYSEaPfu3Xr//ffl6OhY4dsDgOqGMAqg2ujcubPmz5+vV199VR06dNCKFSsUHR1dqs+OGzdObdq0Ubdu3dSoUSPt2LGjWJs77rhDUVFReuGFF+Tt7a2IiIgS+1q2bJmCgoI0ePBgBQcHyzAMffXVV8VOzVeEkJAQNW7cWB07dtQLL7ygdu3aaf/+/bZpqADgdmcxKuoiJwAAAOAmMTIKAAAA0xBGAQAAYBrCKAAAAExDGAUAAIBpCKMAAAAwDWEUAAAApiGMAgAAwDSEUQAAAJiGMAoAAADTEEYBAABgGsIoAAAATEMYBQAAgGn+P0Y2ZaNoSWUUAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "fig, ax, df = plot_label_distributions(\n",
    "    dm.client_set_partitioner,\n",
    "    label_name=\"label\",\n",
    "    plot_type=\"bar\",\n",
    "    size_unit=\"absolute\",\n",
    "    partition_id_axis=\"x\",\n",
    "    legend=True,\n",
    "    verbose_labels=True,\n",
    "    title=\"Per Partition Labels Distribution\",\n",
    ")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Flower Client App"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_parameters(model: DenseNet1dModule) -> list:\n",
    "    return [val.cpu().numpy() for _, val in model.state_dict().items()]\n",
    "\n",
    "\n",
    "def set_parameters(model: DenseNet1dModule, parameters):\n",
    "    params_dict = zip(model.state_dict().keys(), parameters)\n",
    "    state_dict = OrderedDict({k: torch.tensor(v) for k, v in params_dict})\n",
    "    model.load_state_dict(state_dict, strict=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "class FlowerClient(NumPyClient):\n",
    "    def __init__(\n",
    "        self,\n",
    "        context: Context,\n",
    "        train_dataloader: DataLoader,\n",
    "        valid_dataloader: DataLoader,\n",
    "        max_epochs: int,\n",
    "    ):\n",
    "        # disable unnecessary logging for each client\n",
    "        logging.getLogger(\"lightning.pytorch.utilities.rank_zero\").disabled = True\n",
    "        logging.getLogger(\"lightning.pytorch.accelerators.cuda\").disabled = True\n",
    "\n",
    "        self.model = None\n",
    "        self.m_context = context\n",
    "        self.train_dataloader = train_dataloader\n",
    "        self.valid_dataloader = valid_dataloader\n",
    "        self.max_epochs = max_epochs\n",
    "\n",
    "    def get_parameters(self, config):\n",
    "        return get_parameters(self.model)\n",
    "\n",
    "    def fit(self, parameters, config):\n",
    "        default_root_dir = Path(\n",
    "            f\"logs/federated_client/client_{self.m_context.node_id}\"\n",
    "        )\n",
    "        lr = config[\"lr\"]\n",
    "        \n",
    "        # self.model = DenseNet1dModule(\n",
    "        #     num_classes=dm.num_classes,\n",
    "        #     show_valid_cm=False,\n",
    "        #     memory_efficient=False,\n",
    "        #     lr=lr,\n",
    "        # )\n",
    "        self.model = DenseNet1dModuleFL(\n",
    "            num_classes=dm.num_classes,\n",
    "            show_valid_cm=False,\n",
    "            memory_efficient=False,\n",
    "            lr=lr,\n",
    "            proximal_mu=config[\"proximal_mu\"],\n",
    "        )\n",
    "\n",
    "        # remove previous round log files\n",
    "        # shutil.rmtree(default_root_dir, ignore_errors=True)\n",
    "\n",
    "        # get the global model from the server\n",
    "        set_parameters(self.model, parameters)\n",
    "\n",
    "        # define trainer\n",
    "        # checkpoint_callback = ModelCheckpoint(\n",
    "        #     monitor=\"valid_loss\",\n",
    "        #     mode=\"min\",\n",
    "        #     save_top_k=1,\n",
    "        #     save_last=False,\n",
    "        #     enable_version_counter=False,\n",
    "        # )\n",
    "        # early_stopping_callback = EarlyStopping(\n",
    "        #     monitor=\"valid_loss\", patience=8, mode=\"min\"\n",
    "        # )\n",
    "\n",
    "        trainer = L.Trainer(\n",
    "            max_epochs=self.max_epochs,\n",
    "            enable_progress_bar=False,\n",
    "            enable_model_summary=False,\n",
    "            logger=False,\n",
    "            # callbacks=[checkpoint_callback, early_stopping_callback],\n",
    "            enable_checkpointing=False,\n",
    "            default_root_dir=default_root_dir,\n",
    "        )\n",
    "\n",
    "        # train the model\n",
    "        trainer.fit(self.model, self.train_dataloader, self.valid_dataloader)\n",
    "\n",
    "        # return the best model to the server\n",
    "        # best_model = DenseNet1dModuleFL.load_from_checkpoint(\n",
    "        #     checkpoint_callback.best_model_path\n",
    "        # )\n",
    "        # print(checkpoint_callback.best_model_path)\n",
    "        return get_parameters(self.model), len(self.train_dataloader.dataset), {}\n",
    "\n",
    "\n",
    "def client_fn(context: Context) -> Client:\n",
    "    \"\"\"Construct a Client that will be run in a ClientApp.\"\"\"\n",
    "\n",
    "    # Read the node_config to fetch data partition associated to this node\n",
    "    partition_id = context.node_config[\"partition-id\"]\n",
    "    train_dataloader, valid_dataloader = dm.client_dataloaders(partition_id)\n",
    "\n",
    "    # Read run_config to fetch hyperparameters relevant to this run\n",
    "    return FlowerClient(\n",
    "        context, train_dataloader, valid_dataloader, MAX_EPOCHS\n",
    "    ).to_client()\n",
    "\n",
    "\n",
    "client_app = ClientApp(client_fn=client_fn)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Flower Server App"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# The `evaluate` function will be called by Flower after every round\n",
    "def evaluate(\n",
    "    server_round: int,\n",
    "    parameters: NDArrays,\n",
    "    config: Dict[str, Scalar],\n",
    ") -> Optional[Tuple[float, Dict[str, Scalar]]]:\n",
    "    \"\"\"Server-side parameter evaluation\"\"\"\n",
    "    default_root_dir = Path(\"logs/federated_server\")\n",
    "\n",
    "    model = DenseNet1dModule(num_classes=dm.num_classes, memory_efficient=False)\n",
    "    set_parameters(model, parameters)  # Update model with the latest parameters\n",
    "\n",
    "    trainer = L.Trainer(\n",
    "        enable_progress_bar=False, enable_model_summary=False, logger=False\n",
    "    )\n",
    "\n",
    "    # Evaluate on the train set\n",
    "    # We place train evaluation on the server side for convenience.\n",
    "    # In a real-world scenario, this should be done on the client side.\n",
    "    train_result = trainer.validate(model, train_loader, verbose=False)[0]\n",
    "    for key in [\"loss\", \"acc\", \"f1\"]:\n",
    "        train_result[f\"train_{key}\"] = train_result.pop(f\"valid_{key}\")\n",
    "    wandb.log(train_result, step=server_round)\n",
    "\n",
    "    # Evaluate on the valid set\n",
    "    valid_result = trainer.validate(model, valid_loader, verbose=False)[0]\n",
    "    wandb.log(valid_result, step=server_round)\n",
    "\n",
    "    result = {**train_result, **valid_result}\n",
    "\n",
    "    # Save the model checkpoint\n",
    "    # trainer.save_checkpoint(default_root_dir / f\"model_round_{server_round}.ckpt\")\n",
    "    trainer.save_checkpoint(default_root_dir / f\"model_round_last.ckpt\")\n",
    "    return valid_result[\"valid_loss\"], result\n",
    "\n",
    "\n",
    "def fit_config(server_round: int):\n",
    "    lr = 1e-3 * 0.5 ** (server_round // 8)\n",
    "    config = {\n",
    "        \"server_round\": server_round,\n",
    "        \"lr\": lr,\n",
    "    }\n",
    "    wandb.log({\"learning_rate\": lr})\n",
    "    return config\n",
    "\n",
    "\n",
    "def server_fn(context: Context) -> ServerAppComponents:\n",
    "    \"\"\"Construct components for ServerApp.\"\"\"\n",
    "\n",
    "    # Convert model parameters to flwr.common.Parameters\n",
    "    init_model = DenseNet1dModule(num_classes=dm.num_classes, memory_efficient=False)\n",
    "    ndarrays = get_parameters(init_model)\n",
    "    initial_parameters = ndarrays_to_parameters(ndarrays)\n",
    "\n",
    "    # Define strategy\n",
    "    # strategy = FedAvg(\n",
    "    #     fraction_fit=1.0,\n",
    "    #     fraction_evaluate=0,\n",
    "    #     min_fit_clients=NUM_CLIENTS,\n",
    "    #     min_available_clients=NUM_CLIENTS,\n",
    "    #     initial_parameters=initial_parameters,\n",
    "    #     evaluate_fn=evaluate,\n",
    "    #     on_fit_config_fn=fit_config,\n",
    "    # )\n",
    "    strategy = FedProx(\n",
    "        fraction_fit=1.0,\n",
    "        fraction_evaluate=0,\n",
    "        min_fit_clients=NUM_CLIENTS,\n",
    "        min_available_clients=NUM_CLIENTS,\n",
    "        initial_parameters=initial_parameters,\n",
    "        evaluate_fn=evaluate,\n",
    "        on_fit_config_fn=fit_config,\n",
    "        proximal_mu=PROXIMAL_MU,\n",
    "    )\n",
    "\n",
    "    # Construct ServerConfig\n",
    "    config = ServerConfig(num_rounds=NUM_ROUNDS)\n",
    "\n",
    "    return ServerAppComponents(strategy=strategy, config=config)\n",
    "\n",
    "\n",
    "server_app = ServerApp(server_fn=server_fn)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Run Simulation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[92mINFO \u001b[0m:      Starting Flower ServerApp, config: num_rounds=20, no round_timeout\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [INIT]\n",
      "\u001b[92mINFO \u001b[0m:      Using initial global parameters provided by strategy\n",
      "\u001b[92mINFO \u001b[0m:      Starting evaluation of initial global parameters\n",
      "\u001b[92mINFO \u001b[0m:      initial parameters (loss, other metrics): 0.9631854295730591, {'train_loss': 0.961961567401886, 'train_acc': 0.3333333432674408, 'train_f1': 0.25393250584602356, 'valid_loss': 0.9631854295730591, 'valid_acc': 0.3333333432674408, 'valid_f1': 0.25406351685523987}\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 1]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[93mWARNING \u001b[0m:   No fit_metrics_aggregation_fn provided\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (1, 0.8308319449424744, {'train_loss': 0.806323766708374, 'train_acc': 0.47564947605133057, 'train_f1': 0.4038085341453552, 'valid_loss': 0.8308319449424744, 'valid_acc': 0.43949443101882935, 'valid_f1': 0.3760335147380829}, 91.61172272799968)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 2]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (2, 0.5790023803710938, {'train_loss': 0.5188339948654175, 'train_acc': 0.7773808836936951, 'train_f1': 0.7618861198425293, 'valid_loss': 0.5790023803710938, 'valid_acc': 0.7489527463912964, 'valid_f1': 0.7276899218559265}, 174.93859168599965)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 3]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (3, 0.5121661424636841, {'train_loss': 0.4590383768081665, 'train_acc': 0.8085031509399414, 'train_f1': 0.7985139489173889, 'valid_loss': 0.5121661424636841, 'valid_acc': 0.7923908233642578, 'valid_f1': 0.7815496325492859}, 258.53258323399996)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 4]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (4, 0.499719500541687, {'train_loss': 0.43921157717704773, 'train_acc': 0.829606294631958, 'train_f1': 0.8179240226745605, 'valid_loss': 0.499719500541687, 'valid_acc': 0.7936081290245056, 'valid_f1': 0.7854605317115784}, 342.7252895399997)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 5]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (5, 0.47921130061149597, {'train_loss': 0.4167477786540985, 'train_acc': 0.8378348350524902, 'train_f1': 0.8331292271614075, 'valid_loss': 0.47921130061149597, 'valid_acc': 0.8013215065002441, 'valid_f1': 0.7922403216362}, 426.80284313699985)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 6]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (6, 0.48457467555999756, {'train_loss': 0.41070356965065, 'train_acc': 0.845561146736145, 'train_f1': 0.836564302444458, 'valid_loss': 0.48457467555999756, 'valid_acc': 0.8157381415367126, 'valid_f1': 0.8079231977462769}, 510.860256381)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 7]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (7, 0.4794073700904846, {'train_loss': 0.4039249122142792, 'train_acc': 0.8492422103881836, 'train_f1': 0.8486757278442383, 'valid_loss': 0.4794073700904846, 'valid_acc': 0.8017635345458984, 'valid_f1': 0.8017292022705078}, 596.149063505)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 8]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (8, 0.45658549666404724, {'train_loss': 0.3532158136367798, 'train_acc': 0.8611042499542236, 'train_f1': 0.8592208027839661, 'valid_loss': 0.45658549666404724, 'valid_acc': 0.8014336824417114, 'valid_f1': 0.8042011857032776}, 680.788465737)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 9]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (9, 0.47175344824790955, {'train_loss': 0.3401836156845093, 'train_acc': 0.8637088537216187, 'train_f1': 0.8681493997573853, 'valid_loss': 0.47175344824790955, 'valid_acc': 0.7918398380279541, 'valid_f1': 0.803240180015564}, 765.6810374799998)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 10]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (10, 0.4902036786079407, {'train_loss': 0.34396421909332275, 'train_acc': 0.870688796043396, 'train_f1': 0.8716286420822144, 'valid_loss': 0.4902036786079407, 'valid_acc': 0.8052101135253906, 'valid_f1': 0.8099132776260376}, 851.0973096919997)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 11]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (11, 0.48019951581954956, {'train_loss': 0.32944589853286743, 'train_acc': 0.8752042651176453, 'train_f1': 0.8746302127838135, 'valid_loss': 0.48019951581954956, 'valid_acc': 0.8177118301391602, 'valid_f1': 0.8187859058380127}, 936.743134153)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 12]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (12, 0.48333796858787537, {'train_loss': 0.3156782388687134, 'train_acc': 0.8808449506759644, 'train_f1': 0.8828185796737671, 'valid_loss': 0.48333796858787537, 'valid_acc': 0.8060735464096069, 'valid_f1': 0.814315915107727}, 1021.31931239)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 13]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 5 results and 0 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (13, 0.4954439699649811, {'train_loss': 0.3065952956676483, 'train_acc': 0.8857532739639282, 'train_f1': 0.8818209171295166, 'valid_loss': 0.4954439699649811, 'valid_acc': 0.8183214664459229, 'valid_f1': 0.8134680390357971}, 1107.255692018)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 14]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[33m(raylet)\u001b[0m [2024-11-30 05:14:16,921 C 214126 214154] (raylet) store.cc:487:  Check failed: 0 \n",
      "\u001b[33m(raylet)\u001b[0m *** StackTrace Information ***\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0xb8124a) [0x5b24684fa24a] ray::operator<<()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0xb82a07) [0x5b24684fba07] ray::SpdLogMessage::Flush()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0xb82ea7) [0x5b24684fbea7] ray::RayLog::~RayLog()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0x3f24c8) [0x5b2467d6b4c8] plasma::PlasmaStore::ProcessMessage()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0x3eb575) [0x5b2467d64575] std::_Function_handler<>::_M_invoke()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0x5a239d) [0x5b2467f1b39d] ray::ClientConnection::ProcessMessage()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0x5b1fae) [0x5b2467f2afae] EventTracker::RecordExecution()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0x599072) [0x5b2467f12072] boost::asio::detail::binder2<>::operator()()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0x5997c8) [0x5b2467f127c8] boost::asio::detail::reactive_socket_recv_op<>::do_complete()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0xc62acb) [0x5b24685dbacb] boost::asio::detail::scheduler::do_run_one()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0xc65059) [0x5b24685de059] boost::asio::detail::scheduler::run()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0xc65572) [0x5b24685de572] boost::asio::io_context::run()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0x3ea7b8) [0x5b2467d637b8] plasma::PlasmaStoreRunner::Start()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0x3874f5) [0x5b2467d004f5] std::thread::_State_impl<>::_M_run()\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0xcbd380) [0x5b2468636380] execute_native_thread_routine\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: dd19bf3ba7f5380d741de1ac01000000\n",
      "\tpid: 214987\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its node has died. Node Id: 16192aada335fc72130bb211ccb6fb0ecc2fb1e389cd2093c1d72976\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: 9b76dcdab6e91016eb9947ba01000000\n",
      "\tpid: 214982\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its owner has died. Owner Id: 01000000ffffffffffffffffffffffffffffffffffffffffffffffff Owner Ip address: 140.120.13.231 Owner worker exit type: SYSTEM_ERROR Worker exit detail: Owner's node has crashed.\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: cf0bcaa4ad6e90233553e16601000000\n",
      "\tpid: 214983\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its node has died. Node Id: 16192aada335fc72130bb211ccb6fb0ecc2fb1e389cd2093c1d72976\n",
      "\u001b[91mERROR \u001b[0m:     The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: e29f5ad222f84d730a5a82fb01000000\n",
      "\tpid: 214984\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its node has died. Node Id: 16192aada335fc72130bb211ccb6fb0ecc2fb1e389cd2093c1d72976\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 186, in process_message\n",
      "    raise ex\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 174, in process_message\n",
      "    ) = self.pool.fetch_result_and_return_actor_to_pool(future)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 477, in fetch_result_and_return_actor_to_pool\n",
      "    _, out_mssg, updated_context = ray.get(future)\n",
      "                                   ^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 2667, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 866, in get_objects\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: 9b76dcdab6e91016eb9947ba01000000\n",
      "\tpid: 214982\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its owner has died. Owner Id: 01000000ffffffffffffffffffffffffffffffffffffffffffffffff Owner Ip address: 140.120.13.231 Owner worker exit type: SYSTEM_ERROR Worker exit detail: Owner's node has crashed.\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 186, in process_message\n",
      "    raise ex\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 174, in process_message\n",
      "    ) = self.pool.fetch_result_and_return_actor_to_pool(future)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 477, in fetch_result_and_return_actor_to_pool\n",
      "    _, out_mssg, updated_context = ray.get(future)\n",
      "                                   ^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 2667, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 866, in get_objects\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: dd19bf3ba7f5380d741de1ac01000000\n",
      "\tpid: 214987\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its node has died. Node Id: 16192aada335fc72130bb211ccb6fb0ecc2fb1e389cd2093c1d72976\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: d452bfe2ac9a184bd8f0949d01000000\n",
      "\tpid: 214986\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its node has died. Node Id: 16192aada335fc72130bb211ccb6fb0ecc2fb1e389cd2093c1d72976\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 186, in process_message\n",
      "    raise ex\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 174, in process_message\n",
      "    ) = self.pool.fetch_result_and_return_actor_to_pool(future)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 477, in fetch_result_and_return_actor_to_pool\n",
      "    _, out_mssg, updated_context = ray.get(future)\n",
      "                                   ^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 2667, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 866, in get_objects\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: cf0bcaa4ad6e90233553e16601000000\n",
      "\tpid: 214983\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its node has died. Node Id: 16192aada335fc72130bb211ccb6fb0ecc2fb1e389cd2093c1d72976\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 186, in process_message\n",
      "    raise ex\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 174, in process_message\n",
      "    ) = self.pool.fetch_result_and_return_actor_to_pool(future)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 477, in fetch_result_and_return_actor_to_pool\n",
      "    _, out_mssg, updated_context = ray.get(future)\n",
      "                                   ^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 2667, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 866, in get_objects\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: e29f5ad222f84d730a5a82fb01000000\n",
      "\tpid: 214984\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its node has died. Node Id: 16192aada335fc72130bb211ccb6fb0ecc2fb1e389cd2093c1d72976\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 186, in process_message\n",
      "    raise ex\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 174, in process_message\n",
      "    ) = self.pool.fetch_result_and_return_actor_to_pool(future)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 477, in fetch_result_and_return_actor_to_pool\n",
      "    _, out_mssg, updated_context = ray.get(future)\n",
      "                                   ^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/client_mode_hook.py\", line 103, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 2667, in get\n",
      "    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/worker.py\", line 866, in get_objects\n",
      "    raise value\n",
      "ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.\n",
      "\tclass_name: ClientAppActor\n",
      "\tactor_id: d452bfe2ac9a184bd8f0949d01000000\n",
      "\tpid: 214986\n",
      "\tnamespace: 8bfae045-d671-4f41-b56b-707f5b6324db\n",
      "\tip: 140.120.13.231\n",
      "The actor is dead because its node has died. Node Id: 16192aada335fc72130bb211ccb6fb0ecc2fb1e389cd2093c1d72976\n",
      "\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 0 results and 5 failures\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33m(raylet)\u001b[0m The node with node id: 16192aada335fc72130bb211ccb6fb0ecc2fb1e389cd2093c1d72976 and address: 140.120.13.231 and node name: 140.120.13.231 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a \t(1) raylet crashes unexpectedly (OOM, preempted node, etc.) \n",
      "\t(2) raylet has lagging heartbeats due to slow network or busy workload.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2025, in ray._raylet.execute_task\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2065, in ray._raylet.execute_task\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4590, in ray._raylet.CoreWorker.store_task_outputs\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4477, in ray._raylet.CoreWorker.store_task_output\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2281, in ray._raylet.task_execution_handler\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2177, in ray._raylet.execute_task_with_cancellation_handler\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 1832, in ray._raylet.execute_task\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 1833, in ray._raylet.execute_task\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2071, in ray._raylet.execute_task\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 1094, in ray._raylet.store_task_errors\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/utils.py\", line 178, in push_error_to_driver\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m     worker.core_worker.push_error(job_id, error_type, message, time.time())\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4879, in ray._raylet.CoreWorker.push_error\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2320, in ray._raylet.task_execution_handler\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/utils.py\", line 178, in push_error_to_driver\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m     worker.core_worker.push_error(job_id, error_type, message, time.time())\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4879, in ray._raylet.CoreWorker.push_error\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m Exception ignored in: 'ray._raylet.task_execution_handler'\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2320, in ray._raylet.task_execution_handler\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/utils.py\", line 178, in push_error_to_driver\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m     worker.core_worker.push_error(job_id, error_type, message, time.time())\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4879, in ray._raylet.CoreWorker.push_error\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m   File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\u001b[33m(raylet)\u001b[0m /home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/core/src/ray/raylet/raylet(+0x41e027) [0x5b2467d97027] std::_Function_handler<>::_M_invoke()\n",
      "\u001b[36m(ClientAppActor pid=214987)\u001b[0m \u001b[32m [repeated 7x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)\u001b[0m\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (14, 0.4954439699649811, {'train_loss': 0.3065952956676483, 'train_acc': 0.8857532739639282, 'train_f1': 0.8818209171295166, 'valid_loss': 0.4954439699649811, 'valid_acc': 0.8183214664459229, 'valid_f1': 0.8134680390357971}, 1136.569954181)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 15]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 460, in submit\n",
      "    future = actor_fn(actor, app_fn, mssg, cid, context)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 166, in <lambda>\n",
      "    lambda a, a_fn, mssg, cid, state: a.run.remote(a_fn, mssg, cid, state),\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 202, in remote\n",
      "    return self._remote(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/util/tracing/tracing_helper.py\", line 426, in _start_span\n",
      "    return method(self, args, kwargs, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 327, in _remote\n",
      "    return invocation(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 308, in invocation\n",
      "    return actor._actor_method_call(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 1440, in _actor_method_call\n",
      "    object_refs = worker.core_worker.submit_actor_task(\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"python/ray/_raylet.pyx\", line 4180, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 4185, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 864, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 855, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 949, in ray._raylet.prepare_args_internal\n",
      "  File \"python/ray/_raylet.pyx\", line 3709, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref\n",
      "  File \"python/ray/_raylet.pyx\", line 3527, in ray._raylet.CoreWorker._create_put_buffer\n",
      "  File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 460, in submit\n",
      "    future = actor_fn(actor, app_fn, mssg, cid, context)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 166, in <lambda>\n",
      "    lambda a, a_fn, mssg, cid, state: a.run.remote(a_fn, mssg, cid, state),\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 202, in remote\n",
      "    return self._remote(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/util/tracing/tracing_helper.py\", line 426, in _start_span\n",
      "    return method(self, args, kwargs, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 327, in _remote\n",
      "    return invocation(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 308, in invocation\n",
      "    return actor._actor_method_call(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 1440, in _actor_method_call\n",
      "    object_refs = worker.core_worker.submit_actor_task(\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"python/ray/_raylet.pyx\", line 4180, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 4185, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 864, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 855, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 949, in ray._raylet.prepare_args_internal\n",
      "  File \"python/ray/_raylet.pyx\", line 3709, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref\n",
      "  File \"python/ray/_raylet.pyx\", line 3527, in ray._raylet.CoreWorker._create_put_buffer\n",
      "  File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 460, in submit\n",
      "    future = actor_fn(actor, app_fn, mssg, cid, context)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 166, in <lambda>\n",
      "    lambda a, a_fn, mssg, cid, state: a.run.remote(a_fn, mssg, cid, state),\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 202, in remote\n",
      "    return self._remote(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/util/tracing/tracing_helper.py\", line 426, in _start_span\n",
      "    return method(self, args, kwargs, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 327, in _remote\n",
      "    return invocation(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 308, in invocation\n",
      "    return actor._actor_method_call(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 1440, in _actor_method_call\n",
      "    object_refs = worker.core_worker.submit_actor_task(\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"python/ray/_raylet.pyx\", line 4180, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 4185, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 864, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 855, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 949, in ray._raylet.prepare_args_internal\n",
      "  File \"python/ray/_raylet.pyx\", line 3709, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref\n",
      "  File \"python/ray/_raylet.pyx\", line 3527, in ray._raylet.CoreWorker._create_put_buffer\n",
      "  File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 460, in submit\n",
      "    future = actor_fn(actor, app_fn, mssg, cid, context)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 166, in <lambda>\n",
      "    lambda a, a_fn, mssg, cid, state: a.run.remote(a_fn, mssg, cid, state),\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 202, in remote\n",
      "    return self._remote(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/util/tracing/tracing_helper.py\", line 426, in _start_span\n",
      "    return method(self, args, kwargs, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 327, in _remote\n",
      "    return invocation(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 308, in invocation\n",
      "    return actor._actor_method_call(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 1440, in _actor_method_call\n",
      "    object_refs = worker.core_worker.submit_actor_task(\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"python/ray/_raylet.pyx\", line 4180, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 4185, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 864, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 855, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 949, in ray._raylet.prepare_args_internal\n",
      "  File \"python/ray/_raylet.pyx\", line 3709, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref\n",
      "  File \"python/ray/_raylet.pyx\", line 3527, in ray._raylet.CoreWorker._create_put_buffer\n",
      "  File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 460, in submit\n",
      "    future = actor_fn(actor, app_fn, mssg, cid, context)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 166, in <lambda>\n",
      "    lambda a, a_fn, mssg, cid, state: a.run.remote(a_fn, mssg, cid, state),\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 202, in remote\n",
      "    return self._remote(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/util/tracing/tracing_helper.py\", line 426, in _start_span\n",
      "    return method(self, args, kwargs, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 327, in _remote\n",
      "    return invocation(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 308, in invocation\n",
      "    return actor._actor_method_call(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 1440, in _actor_method_call\n",
      "    object_refs = worker.core_worker.submit_actor_task(\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"python/ray/_raylet.pyx\", line 4180, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 4185, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 864, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 855, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 949, in ray._raylet.prepare_args_internal\n",
      "  File \"python/ray/_raylet.pyx\", line 3709, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref\n",
      "  File \"python/ray/_raylet.pyx\", line 3527, in ray._raylet.CoreWorker._create_put_buffer\n",
      "  File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 0 results and 5 failures\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m Traceback (most recent call last):\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2071, in ray._raylet.execute_task\u001b[32m [repeated 5x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4590, in ray._raylet.CoreWorker.store_task_outputs\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4477, in ray._raylet.CoreWorker.store_task_output\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m   File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m ray.exceptions.RaySystemError: System error: Broken pipe\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m During handling of the above exception, another exception occurred:\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2320, in ray._raylet.task_execution_handler\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2177, in ray._raylet.execute_task_with_cancellation_handler\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m   File \"python/ray/_raylet.pyx\", line 1094, in ray._raylet.store_task_errors\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m   File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/utils.py\", line 178, in push_error_to_driver\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m     worker.core_worker.push_error(job_id, error_type, message, time.time())\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4879, in ray._raylet.CoreWorker.push_error\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m Exception ignored in: 'ray._raylet.task_execution_handler'\n",
      "\u001b[36m(ClientAppActor pid=214984)\u001b[0m \u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (15, 0.4954439699649811, {'train_loss': 0.3065952956676483, 'train_acc': 0.8857532739639282, 'train_f1': 0.8818209171295166, 'valid_loss': 0.4954439699649811, 'valid_acc': 0.8183214664459229, 'valid_f1': 0.8134680390357971}, 1145.4914811139997)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 16]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 460, in submit\n",
      "    future = actor_fn(actor, app_fn, mssg, cid, context)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 166, in <lambda>\n",
      "    lambda a, a_fn, mssg, cid, state: a.run.remote(a_fn, mssg, cid, state),\n",
      "                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 202, in remote\n",
      "    return self._remote(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/util/tracing/tracing_helper.py\", line 426, in _start_span\n",
      "    return method(self, args, kwargs, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 327, in _remote\n",
      "    return invocation(args, kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 308, in invocation\n",
      "    return actor._actor_method_call(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/actor.py\", line 1440, in _actor_method_call\n",
      "    object_refs = worker.core_worker.submit_actor_task(\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"python/ray/_raylet.pyx\", line 4180, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 4185, in ray._raylet.CoreWorker.submit_actor_task\n",
      "  File \"python/ray/_raylet.pyx\", line 864, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 855, in ray._raylet.prepare_args_and_increment_put_refs\n",
      "  File \"python/ray/_raylet.pyx\", line 949, in ray._raylet.prepare_args_internal\n",
      "  File \"python/ray/_raylet.pyx\", line 3709, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref\n",
      "  File \"python/ray/_raylet.pyx\", line 3527, in ray._raylet.CoreWorker._create_put_buffer\n",
      "  File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\n",
      "ray.exceptions.RaySystemError: System error: Broken pipe\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 0 results and 5 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (16, 0.4954439699649811, {'train_loss': 0.3065952956676483, 'train_acc': 0.8857532739639282, 'train_f1': 0.8818209171295166, 'valid_loss': 0.4954439699649811, 'valid_acc': 0.8183214664459229, 'valid_f1': 0.8134680390357971}, 1152.179929501)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 17]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 0 results and 5 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (17, 0.4954439699649811, {'train_loss': 0.3065952956676483, 'train_acc': 0.8857532739639282, 'train_f1': 0.8818209171295166, 'valid_loss': 0.4954439699649811, 'valid_acc': 0.8183214664459229, 'valid_f1': 0.8134680390357971}, 1159.734010794)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 18]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 0 results and 5 failures\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4590, in ray._raylet.CoreWorker.store_task_outputs\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4477, in ray._raylet.CoreWorker.store_task_output\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2177, in ray._raylet.execute_task_with_cancellation_handler\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m   File \"python/ray/_raylet.pyx\", line 1094, in ray._raylet.store_task_errors\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m Exception ignored in: 'ray._raylet.task_execution_handler'\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m Traceback (most recent call last):\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2071, in ray._raylet.execute_task\u001b[32m [repeated 5x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m   File \"python/ray/_raylet.pyx\", line 589, in ray._raylet.check_status\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m ray.exceptions.RaySystemError: System error: Broken pipe\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m During handling of the above exception, another exception occurred:\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m   File \"python/ray/_raylet.pyx\", line 2320, in ray._raylet.task_execution_handler\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m   File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/ray/_private/utils.py\", line 178, in push_error_to_driver\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m     worker.core_worker.push_error(job_id, error_type, message, time.time())\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m   File \"python/ray/_raylet.pyx\", line 4879, in ray._raylet.CoreWorker.push_error\u001b[32m [repeated 3x across cluster]\u001b[0m\n",
      "\u001b[36m(ClientAppActor pid=214983)\u001b[0m \u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (18, 0.4954439699649811, {'train_loss': 0.3065952956676483, 'train_acc': 0.8857532739639282, 'train_f1': 0.8818209171295166, 'valid_loss': 0.4954439699649811, 'valid_acc': 0.8183214664459229, 'valid_f1': 0.8134680390357971}, 1166.2118272839998)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 19]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 0 results and 5 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (19, 0.4954439699649811, {'train_loss': 0.3065952956676483, 'train_acc': 0.8857532739639282, 'train_f1': 0.8818209171295166, 'valid_loss': 0.4954439699649811, 'valid_acc': 0.8183214664459229, 'valid_f1': 0.8134680390357971}, 1170.818917562)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [ROUND 20]\n",
      "\u001b[92mINFO \u001b[0m:      configure_fit: strategy sampled 5 clients (out of 5)\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     An exception was raised when processing a message by RayBackend\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     cannot access local variable 'future' where it is not associated with a value\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[91mERROR \u001b[0m:     Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 165, in process_message\n",
      "    future = self.pool.submit(\n",
      "             ^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py\", line 457, in submit\n",
      "    actor = self.pool.pop()\n",
      "            ^^^^^^^^^^^^^^^\n",
      "IndexError: pop from empty list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/vce_api.py\", line 112, in worker\n",
      "    out_mssg, updated_context = backend.process_message(message, context)\n",
      "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/flwr/server/superlink/fleet/vce/backend/raybackend.py\", line 185, in process_message\n",
      "    self.pool.add_actor_back_to_pool(future)\n",
      "                                     ^^^^^^\n",
      "UnboundLocalError: cannot access local variable 'future' where it is not associated with a value\n",
      "\n",
      "\u001b[92mINFO \u001b[0m:      aggregate_fit: received 0 results and 5 failures\n",
      "\u001b[92mINFO \u001b[0m:      fit progress: (20, 0.4954439699649811, {'train_loss': 0.3065952956676483, 'train_acc': 0.8857532739639282, 'train_f1': 0.8818209171295166, 'valid_loss': 0.4954439699649811, 'valid_acc': 0.8183214664459229, 'valid_f1': 0.8134680390357971}, 1175.317275601)\n",
      "\u001b[92mINFO \u001b[0m:      configure_evaluate: no clients selected, skipping evaluation\n",
      "\u001b[92mINFO \u001b[0m:      \n",
      "\u001b[92mINFO \u001b[0m:      [SUMMARY]\n",
      "\u001b[92mINFO \u001b[0m:      Run finished 20 round(s) in 1175.32s\n",
      "\u001b[92mINFO \u001b[0m:      \tHistory (loss, centralized):\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 0: 0.9631854295730591\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 1: 0.8308319449424744\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 2: 0.5790023803710938\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 3: 0.5121661424636841\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 4: 0.499719500541687\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 5: 0.47921130061149597\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 6: 0.48457467555999756\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 7: 0.4794073700904846\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 8: 0.45658549666404724\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 9: 0.47175344824790955\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 10: 0.4902036786079407\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 11: 0.48019951581954956\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 12: 0.48333796858787537\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 13: 0.4954439699649811\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 14: 0.4954439699649811\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 15: 0.4954439699649811\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 16: 0.4954439699649811\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 17: 0.4954439699649811\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 18: 0.4954439699649811\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 19: 0.4954439699649811\n",
      "\u001b[92mINFO \u001b[0m:      \t\tround 20: 0.4954439699649811\n",
      "\u001b[92mINFO \u001b[0m:      \tHistory (metrics, centralized):\n",
      "\u001b[92mINFO \u001b[0m:      \t{'train_acc': [(0, 0.3333333432674408),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (1, 0.47564947605133057),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (2, 0.7773808836936951),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (3, 0.8085031509399414),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (4, 0.829606294631958),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (5, 0.8378348350524902),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (6, 0.845561146736145),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (7, 0.8492422103881836),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (8, 0.8611042499542236),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (9, 0.8637088537216187),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (10, 0.870688796043396),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (11, 0.8752042651176453),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (12, 0.8808449506759644),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (13, 0.8857532739639282),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (14, 0.8857532739639282),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (15, 0.8857532739639282),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (16, 0.8857532739639282),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (17, 0.8857532739639282),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (18, 0.8857532739639282),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (19, 0.8857532739639282),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (20, 0.8857532739639282)],\n",
      "\u001b[92mINFO \u001b[0m:      \t 'train_f1': [(0, 0.25393250584602356),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (1, 0.4038085341453552),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (2, 0.7618861198425293),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (3, 0.7985139489173889),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (4, 0.8179240226745605),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (5, 0.8331292271614075),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (6, 0.836564302444458),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (7, 0.8486757278442383),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (8, 0.8592208027839661),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (9, 0.8681493997573853),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (10, 0.8716286420822144),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (11, 0.8746302127838135),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (12, 0.8828185796737671),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (13, 0.8818209171295166),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (14, 0.8818209171295166),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (15, 0.8818209171295166),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (16, 0.8818209171295166),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (17, 0.8818209171295166),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (18, 0.8818209171295166),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (19, 0.8818209171295166),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (20, 0.8818209171295166)],\n",
      "\u001b[92mINFO \u001b[0m:      \t 'train_loss': [(0, 0.961961567401886),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (1, 0.806323766708374),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (2, 0.5188339948654175),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (3, 0.4590383768081665),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (4, 0.43921157717704773),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (5, 0.4167477786540985),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (6, 0.41070356965065),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (7, 0.4039249122142792),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (8, 0.3532158136367798),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (9, 0.3401836156845093),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (10, 0.34396421909332275),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (11, 0.32944589853286743),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (12, 0.3156782388687134),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (13, 0.3065952956676483),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (14, 0.3065952956676483),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (15, 0.3065952956676483),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (16, 0.3065952956676483),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (17, 0.3065952956676483),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (18, 0.3065952956676483),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (19, 0.3065952956676483),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (20, 0.3065952956676483)],\n",
      "\u001b[92mINFO \u001b[0m:      \t 'valid_acc': [(0, 0.3333333432674408),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (1, 0.43949443101882935),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (2, 0.7489527463912964),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (3, 0.7923908233642578),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (4, 0.7936081290245056),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (5, 0.8013215065002441),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (6, 0.8157381415367126),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (7, 0.8017635345458984),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (8, 0.8014336824417114),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (9, 0.7918398380279541),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (10, 0.8052101135253906),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (11, 0.8177118301391602),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (12, 0.8060735464096069),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (13, 0.8183214664459229),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (14, 0.8183214664459229),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (15, 0.8183214664459229),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (16, 0.8183214664459229),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (17, 0.8183214664459229),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (18, 0.8183214664459229),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (19, 0.8183214664459229),\n",
      "\u001b[92mINFO \u001b[0m:      \t               (20, 0.8183214664459229)],\n",
      "\u001b[92mINFO \u001b[0m:      \t 'valid_f1': [(0, 0.25406351685523987),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (1, 0.3760335147380829),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (2, 0.7276899218559265),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (3, 0.7815496325492859),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (4, 0.7854605317115784),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (5, 0.7922403216362),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (6, 0.8079231977462769),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (7, 0.8017292022705078),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (8, 0.8042011857032776),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (9, 0.803240180015564),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (10, 0.8099132776260376),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (11, 0.8187859058380127),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (12, 0.814315915107727),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (13, 0.8134680390357971),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (14, 0.8134680390357971),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (15, 0.8134680390357971),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (16, 0.8134680390357971),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (17, 0.8134680390357971),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (18, 0.8134680390357971),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (19, 0.8134680390357971),\n",
      "\u001b[92mINFO \u001b[0m:      \t              (20, 0.8134680390357971)],\n",
      "\u001b[92mINFO \u001b[0m:      \t 'valid_loss': [(0, 0.9631854295730591),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (1, 0.8308319449424744),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (2, 0.5790023803710938),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (3, 0.5121661424636841),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (4, 0.499719500541687),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (5, 0.47921130061149597),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (6, 0.48457467555999756),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (7, 0.4794073700904846),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (8, 0.45658549666404724),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (9, 0.47175344824790955),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (10, 0.4902036786079407),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (11, 0.48019951581954956),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (12, 0.48333796858787537),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (13, 0.4954439699649811),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (14, 0.4954439699649811),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (15, 0.4954439699649811),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (16, 0.4954439699649811),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (17, 0.4954439699649811),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (18, 0.4954439699649811),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (19, 0.4954439699649811),\n",
      "\u001b[92mINFO \u001b[0m:      \t                (20, 0.4954439699649811)]}\n",
      "\u001b[92mINFO \u001b[0m:      \n"
     ]
    }
   ],
   "source": [
    "backend_config = {\n",
    "    \"client_resources\": {\"num_cpus\": 1, \"num_gpus\": 1 / (NUM_CLIENTS + 1)}\n",
    "}\n",
    "\n",
    "# Run simulation\n",
    "run_simulation(\n",
    "    server_app=server_app,\n",
    "    client_app=client_app,\n",
    "    num_supernodes=NUM_CLIENTS,\n",
    "    backend_config=backend_config,\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Evaluation and Visualization on the Test set."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "progress_bar_callback = TQDMProgressBar(leave=True)\n",
    "\n",
    "trainer = L.Trainer(\n",
    "    callbacks=[progress_bar_callback],\n",
    "    logger=False,\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Testing DataLoader 0: 100%|██████████| 13/13 [00:00<00:00, 40.62it/s]\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\">┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n",
       "┃<span style=\"font-weight: bold\">        Test metric        </span>┃<span style=\"font-weight: bold\">       DataLoader 0        </span>┃\n",
       "┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩\n",
       "│<span style=\"color: #008080; text-decoration-color: #008080\">         test_acc          </span>│<span style=\"color: #800080; text-decoration-color: #800080\">    0.8001526594161987     </span>│\n",
       "│<span style=\"color: #008080; text-decoration-color: #008080\">          test_f1          </span>│<span style=\"color: #800080; text-decoration-color: #800080\">    0.7982633113861084     </span>│\n",
       "│<span style=\"color: #008080; text-decoration-color: #008080\">         test_loss         </span>│<span style=\"color: #800080; text-decoration-color: #800080\">    0.6207807064056396     </span>│\n",
       "└───────────────────────────┴───────────────────────────┘\n",
       "</pre>\n"
      ],
      "text/plain": [
       "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n",
       "┃\u001b[1m \u001b[0m\u001b[1m       Test metric       \u001b[0m\u001b[1m \u001b[0m┃\u001b[1m \u001b[0m\u001b[1m      DataLoader 0       \u001b[0m\u001b[1m \u001b[0m┃\n",
       "┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩\n",
       "│\u001b[36m \u001b[0m\u001b[36m        test_acc         \u001b[0m\u001b[36m \u001b[0m│\u001b[35m \u001b[0m\u001b[35m   0.8001526594161987    \u001b[0m\u001b[35m \u001b[0m│\n",
       "│\u001b[36m \u001b[0m\u001b[36m         test_f1         \u001b[0m\u001b[36m \u001b[0m│\u001b[35m \u001b[0m\u001b[35m   0.7982633113861084    \u001b[0m\u001b[35m \u001b[0m│\n",
       "│\u001b[36m \u001b[0m\u001b[36m        test_loss        \u001b[0m\u001b[36m \u001b[0m│\u001b[35m \u001b[0m\u001b[35m   0.6207807064056396    \u001b[0m\u001b[35m \u001b[0m│\n",
       "└───────────────────────────┴───────────────────────────┘\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[{'test_loss': 0.6207807064056396, 'test_acc': 0.8001526594161987, 'test_f1': 0.7982633113861084}]\n"
     ]
    }
   ],
   "source": [
    "model = DenseNet1dModule.load_from_checkpoint(\n",
    "    Path(f\"logs/federated_server/model_round_last.ckpt\")\n",
    ")\n",
    "\n",
    "result = trainer.test(model, datamodule=dm)\n",
    "print(result)\n",
    "wandb.log(result[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAekAAAHrCAYAAADrBmWcAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjkuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8hTgPZAAAACXBIWXMAAA9hAAAPYQGoP6dpAABC6klEQVR4nO3dd3xOd//H8fcV2WTZIrH3jBk7UVJq12oopbppVVGq7pa2d6uqRqmf3h1Wl6q6lbbUjBq1ajZGQ+wQYiXIIDm/P3K7Kk1CXMJ14no9H488Hq7v+Z7r+hwi75zz/Z7vsRiGYQgAAJiOk70LAAAAWSOkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAk3K2dwH3W1pammJiYuTl5SWLxWLvcgAADsgwDCUkJMjf319OTtmfLztcSMfExCgwMNDeZQAAoOPHjysgICDb7Q4X0l5eXpIk12r9ZMnnaudqYHbHIj60dwnIQ5Kvpdq7BOQRCQnxql6xjDWTsuNwIX3jErclnyshjdvy9va2dwnIQwhp3KnbDbsycQwAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKWd7F4DcV9Anv3Ys/JeKFvTSoWNnVaPzW1n2K1HERyMGPKywJtUUUNxXqamGDh0/q8VrdmnK3FW6fDU528/o0zFY/bo0VrXyJeTh5qLTcfHasueIxn++TPuiT9+rQ4OdfPHZf7Rt61YdOLBP586dU0pysgoXKaKGwY307HMvqHKVqvYuEfdZ5J+7tXH9Ou3ZvUt7du1UbGz6//u9B49lu8/Fixf12SfTtXL5Mp0+dUpeXl6q36Chnhs0WFWrVb9fpecphPQD6P2hj6qwb/5b9ilfqohWzxqqogW9dORknJaui5Sbq7Ma1S6n0c+106Ot66hl/4mKv5yUYT83V2d9N+kZtWlaXecuXtHvO6OVlHxNZQIKq1tYHS1bH0lIP4BmTJ+mq1cTVaVqVVWunB7IUVEHtGjhD/p5yWL9338+00OtwuxcJe6nGR9P1eqVy3Pc/+yZWPV5rJuOHz+mwkWKqHlIqOLOntWK5cu0ZvUq/d+nM9W0eYt7WHHeREg/YEIbVlLfTo30+YL1erp7s2z7vTu4s4oW9NIn3/2mYR98r7Q0Q5LkXcBdi6cPUnCtshrc5yH9+5NfMuw3bXS42jStri9+2KDhExYoKfmadVvxwt5ycc53bw4MdvXJZ7NUs2ZNubm7Z2j/au5sjXljtEaNfFUbNm2TszM/UhxFUJ26qlylqmrUrKUatWorLKSpUlKyv/o2ZvRrOn78mJqHtNTkaTPk6ekpSVq54lcNGfScRgwdrOVr1it/gQL36xDyBMakHyDubi76eHQv7T10SlO+XHXLvk3rVpAkvf/ZUmtAS1L85SRNmr1CklSveukM+9SvXlp9OzXS1j1H9OK/v80Q0JJ0Oi5ex09fyI1DgcnUb9AgU0BLUp8n+qtU6TKKO3tWB6P+skNlsJennxuol4YMU8tWYSpSpOgt+56KiVHEmlVydnbWm2+/aw1oSWod1kaPdOikCxfOa+GC7+512XkOIf0AGf3cIyobUEiD352na9dSb9k35dr1277f+YtXMrx+smsTSdKM79baXiQeOC7/O3t2cXG1cyUwq72Rf0qSSgYEqmTJgEzbg4MbS5JWr1xxX+vKCwjpB0SNiv56uU8rzV28SRt2HLpt/5W/75ckvfbMI3JysljbvQu4a2j/9LHFOT/+nmGf0AaVJEmbdh1W2YDCGvl0G00bHa4xAzuoSVC53DoU5CH/XbhA0dGHVKZsWZUpW9be5cCkEhOvSpK8fXyy3O7r5ydJ2r9/732rKa/IcwNIkZGRql6dWYA3s1gsmvFmb128fFWjp/yYo33enPaj6lQN1POPtVDbZtW0Y99xubm6qHFQOSUlX9OTr8/Wb9uirP3dXJ1VLrCIpPSwnjSyh9zdXKzbX3umrb7/9Q899a+5unb91mfxyLs+/WSGoqIOKPHqVR08eFBRfx1QsWLFNWXa/ylfPuYjIGsFCxaUJMWcPJnl9hPHj0uSLl28qCtXrih//ltPfHUkeepM+ssvv1TNmjWVlJR0+84OZGB4iOrXKKPXJy/S+UtXbr+DpNhzCWrzzEdasXGfypQsrEdb11G7FjXk5+2pzbsPa/u+4xn6+3p5WP/80ajHtGx9pGo/+o6KNR+ux4Z+qrMXEtSjTT299WLHXD02mMu63yK0cMH3WvrLz4r664BKBgRoyrTpqlmzlr1Lg4nVrB0kV1c3nYs7q3VrIzJsMwxDixZ+b3199crl+1ydueWpkG7YsKFKly6t999/P8f7JCcnKz4+PsPXgySwuJ/GDOqg37ZF6aslm3O8X42K/try3ShVKlNU3Yf8R8Wbv6ryD4/W8A8W6OEm1bR61lBVLP33ZBAnp7+/VQ4ciVXvV7/QX0diFX85SYvX7NYzb34pSXr+sRbyyp95ghEeDF9+850OHT2pHbv3at73C1WmTFn16tlN06d9ZO/SYGJeXt7q9XhfSdLrI4Zq5fJlSkiI1+HoQxr28iBFHzpo7WtxylOxdM+Z8m8jJSVFY8aMUd++fbV589/BU6ZMGT355JOaPHlyjt9r3Lhx8vHxsX4FBgbei5LtZvJrPeXqkk8vvTsvx/s4OzvpmwlPq0QRH4UP+0w/r92jS5cTFXP2kqZ/G6G3/u8nFfLNrzdfaG/d5+aFTb75abMMw8jwnr+u36vYc/HycHdV/RoZZ4XjwePt46MGDYP1xewvVaNmLU2eOEG7d+20d1kwsVeGj9TDbdvp3Lk4DR74rILr1FD7h1tq1YrlGvWvsdZ+3l7e9ivShEw5Jn3+/HnNmDFDcXFxWr9+vSZPnqzOnTvLzc1Njz76qD766CNNnTpVgwcPvu17jRo1SkOHDrW+jo+Pf6CCun1ITV2Iv6ppo8MztLu7pv/T+hf10a+fvSxJeuK1mYo9l6DgmmVVsXRRHTp2Vjv3n8j0ngtXbNf4YV2tt2lJUsKVJJ2/dEUFffLraMz5LGs5FnNexQp5q6ifV24dHkzOxcVF7Tt00p97dmvVyhWqVTvI3iXBpFzd3DTl40+0betmrf9trS6cP6fiJfz1SIdOsih98mqp0mXk6uZm50rNxZQhXbx4cT311FPavn27rl+/rrFjx2rNmjX697//rZo1a+rxxx/X+++/n6OQdnNzk9sD/o/u5+2pFvUrZrnNw93Vus3NNX2iV8livpKkS5cTs9zn0v9WGfPz9szQvvvACYU2rCzff7Rb6/BJb7+cmP2CBnjw3JgUdP78OTtXgrygfoNg1W8QnKHtx/8ukCQ1DG5kj5JMzZSXuyWpf//+kqRmzZpp+vTp+vnnn9W2bVsdO3ZM/fr1U1JSkubOnWvfIk3Ao86LWX5VbvemJOnQsbPWtmOn0s+AT8elj8tXKlNMBTwz/wJTr3opSdLRmIw/dH9eu0eSsvyFILC4n0qXKCRJ2rX/eKbteHBt3px+q16pUmXsWwjyJMMw9M1X6T/Luz/W287VmI9pQ7pSpUoqX7681q9fr6CgIK1du1b58uVTz5499euvv6pv375677337F1mnrR592HFnotXAU+3/41p/31BpUQRH30wrJsk6b8rd2bYb86Pm3T2QoK6P1xX7UNqWts93F00ZdRjcnHJp6Xr/tSJ2Iv34zBwn2zbulVrI9YoLS0tQ/u1a9c0Z9ZMLVr4g9zd3dW+IzP7kb2YmJM6dy4uQ1tSUpLGjB6pPbt2qku3HgyXZMGUl7ul9Ht/n332WT3//PP67LPPNGTIEP3www/68ssvNWLECIWFhemvv/5SRESEQkND7V1unpKccl0v/Xuevv7gKfXpGKyWDStp+95jcndzVXCtMvIu4KHte4/pw1kZF89PuJKkAaPn6oePntP8Sc9o659HdfrsJTWoWUb+RX115GScXnznWzsdFe6VI0eiNXL4UBUsWFDVa9aSn6+fLlw4rwP79+vMmVi5ubnrg4mT5e9f0t6l4j5au2aVZnw81fr62rUUSVJ4t87WthdeHKyQlq0kSZt/36gxo0eqeo1aKuHvr+SkJG3fvk2XLl5Us+YhGvP2u/f3APII04a0JNWqVUsVK1bUypUr1bdvXxUpUkRDhw6Vn5+fPv/8c0np904T0nduScRuNe87QUOeaKVmdSuoTbPqSrmWqoPHzuiHFTv08ddrMq3NLUkrf9+nZn0m6PVnH1HTuuVVp2qgTpy+oKlfrdYHX/yqcxdzdp828o7g4MZ6YdBL2rJ5kw7s26cLF87LxcVFJQMC1bZde/V7coDKlGG1MUdz/vx57d61I1P7zW3nz/89ybR6jZp6uG077dq5Q/v3RcrV1U0VK1fWo916qmv3nrJYLJneC5LF+Oe9NCazbt06jRgxQs8995x1nFqSzpw5o61bt6p9+/bZ75yF+Ph4+fj4yK3mM7LkY61h3NqFrR/buwTkIcm3WTMfuCE+Pl6lihfUpUuX5O2d/W1nph2TvqFx48by9/fXl19+qcTE9NnIhmGoaNGidxzQAADkJaYPaWdnZ/Xr10/BwcFKSUkf8+CyCADAEZh6TPqGjh07qlOnTvYuAwCA+8r0Z9ISZ84AAMeUJ0IaAABHREgDAGBShDQAACZFSAMAYFKENAAAJkVIAwBgUoQ0AAAmRUgDAGBShDQAACZFSAMAYFKENAAAJkVIAwBgUoQ0AAAmRUgDAGBShDQAACZFSAMAYFKENAAAJkVIAwBgUoQ0AAAmRUgDAGBShDQAACZFSAMAYFKENAAAJkVIAwBgUoQ0AAAmRUgDAGBShDQAACZFSAMAYFKENAAAJkVIAwBgUoQ0AAAmRUgDAGBShDQAACZFSAMAYFKENAAAJkVIAwBgUoQ0AAAmRUgDAGBShDQAACZFSAMAYFKENAAAJkVIAwBgUoQ0AAAmRUgDAGBShDQAACZFSAMAYFKENAAAJkVIAwBgUoQ0AAAmRUgDAGBShDQAACZFSAMAYFKENAAAJkVIAwBgUoQ0AAAmRUgDAGBShDQAACblbO8C7OVYxIfy9va2dxkwuZgLifYuAXlIUW83e5eAPCKfkyVH/TiTBgDApAhpAABMipAGAMCkCGkAAEyKkAYAwKQIaQAATIqQBgDApAhpAABMipAGAMCkCGkAAEyKkAYAwKQIaQAATIqQBgDApAhpAABMipAGAMCkCGkAAEyKkAYAwKQIaQAATIqQBgDApAhpAABMipAGAMCkbArp2NhY/fbbb4qNjc3QfujQIYWHh6tGjRpq166dNm3alCtFAgDgiGwK6ffff18tW7bUpUuXrG3x8fFq1qyZvv/+e+3du1fLli1Tq1atFBUVlWvFAgDgSGwK6YiICFWrVk2VKlWyts2ePVuxsbHq1auXDhw4oEmTJikxMVETJ07MtWIBAHAkNoX0yZMnVa5cuQxtP//8s5ydnTVlyhRVrFhRQ4YMUe3atbV27dpcKRQAAEdjU0gnJCTI09PT+jo1NVW///676tWrp8KFC1vbq1SpohMnTtx9lQAAOCCbQtrf31/79++3vl6/fr0uX76s0NDQDP2uX78uV1fXuyoQAABHZVNIN27cWLt379aUKVO0Z88e/etf/5LFYlHHjh0z9Nu3b59KliyZK4UCAOBobArpUaNGyc3NTcOGDVNQUJA2bNig0NBQNWnSxNrnyJEj2rt3r4KDg3OtWAAAHImzLTtVr15d69ev10cffaS4uDjVq1dPr776aoY+v/76q2rXrq0uXbrkRp0AADgci2EYhr2LuJ/i4+Pl4+Oj2HOX5O3tbe9yYHIxFxLtXQLykKLebvYuAXlEfHy8Shb106VLt84ilgUFAMCkbArpqKgozZ07V4cPH87QvmnTJjVq1EgFChRQtWrVtHDhwlwpEgAAR2RTSE+cOFEDBgyQi4uLtS02NlZt2rTRli1blJiYqP379+uxxx7T9u3bc61YAAAciU0hvX79egUFBSkgIMDaNnPmTCUkJGjo0KFKTEzUwoULlZaWpkmTJuVasQAAOBKbQvrUqVMqXbp0hrZly5bJzc1NY8eOlaurq7p06aLg4GBt3rw5VwoFAMDR2BTSSUlJypcvn/V1cnKytm7dquDgYBUoUMDaXrZsWcXExNx9lQAAOCCbQjogIEC7d++2vl65cqWSkpL00EMPZeiXmJio/Pnz312FAAA4KJtC+qGHHlJUVJSGDBmiJUuWaOTIkbJYLOrcuXOGfnv27FFgYGCuFAoAgKOxeVlQX19fTZs2TV26dNHevXvVs2dP1a5d29onMjJShw4dUtOmTXOtWAAAHIlNy4KWKlVKu3bt0ueff66zZ8+qXr166t+/f4Y+O3bsUOfOndWzZ8/cqBMAAIfDsqDALbAsKO4Ey4Iip1gWFACAPM6my903S0hI0KFDh5SQkKDsTspbtGhxtx8DAIDDsTmk//zzTw0ZMkQRERHZhvMNqamptn4MAAAOy6aQjoqKUrNmzRQfH6+mTZvq1KlTOnz4sMLDwxUdHa3t27fr+vXr6tSpk3x9fXO5ZAAAHINNY9L//ve/lZCQoFmzZmndunVq3ry5JOnrr7/W77//rsjISDVr1kx79+5l7W4AAGxkU0ivXr1aVatWVb9+/bLcXqFCBf344486e/as3njjjbsqEAAAR2VTSJ85c0bVqlWzvr7xyMqkpCRrm6+vr0JDQ/XTTz/dZYkAADgmm0K6YMGCSk5OzvBako4ePZqp75kzZ2wsDQAAx2ZTSJctWzZDIAcFBckwDH333XfWtri4OEVERKhUqVJ3XyUAAA7IppB++OGH9eeff1qDumPHjipcuLDefvtthYeHa9iwYWrQoIEuXbrEsqAAANjIpluw+vbtq+TkZMXGxqp06dLKnz+/5s2bp549e2r+/PnWfmFhYRo9enSuFQsAgCPJ1bW7r1y5onXr1unChQuqVKmS6tWrl1tvnWtYuxt3grW7cSdYuxs5ldO1u+96WdCb5c+fX23bts3NtwQAwGHxgA0AAEwqR2fSc+fOvasPeeKJJ+5qfwAAHFGOxqSdnJxksVju+M0Nw5DFYjHVAzYYk8adYEwad4IxaeRUro5Jv/nmmzaFNAAAsF2OQnrs2LH3uAwAAPBPuTq7G3lHYmKi1v22VqtXrtC2bVt08uRJ5XNyUukyZdT2kfYa8PSzyp8/v73LhJ1cOH9O38z+VBvWrlbs6Ri5ubmruH9J1WvYRIOGvnbLfd8f+5p+XrRAkjR91jzVqlP/fpSM++zPPbu1cf067d61U7t371Ts6dOSpAPRx2+538IF8/XNV3N16GCUXFxcVDuorl54cbDq1uP7JCs23Sd9+fJlRUdHy9/fX4ULF86yT1xcnGJiYlS+fHlT/bBnTDrdd99+o9dfe1WSVKFCRVWqXFkJly9rxx/bdPnyZZUvX0HfzP8h239fR+GIY9IH9v6pYQOf1KWLF1S2fEWVrVBJVy9f1pHogzp75rQi/jiQ7b7bt/6ul5/pK4vFIsMwHC6kHWlMeuBzT2nViuWZ2m8V0u++PVZzZ38hd3d3NW3eQsnJydq0cYMMw9DU6Z+o9cOOcwvvPb1PetKkSXrrrbe0cePGbH+IHzp0SE2aNNE777yj119/3ZaPwT3k7OKs8N6P68kBz6hCxYrW9jOxsXr6yScUGfmn/v3WGE2ZNt2OVeJ+u3D+nIYNelLJSUkaN+UTNQttnWH73j27st03OTlZE955Q2XLV1T+Al76c9f2e10u7CioTj1VrlJVNWvVVs1atfVQ8yZKSUnOtv/G9es0d/YX8vXz03cLflSZsmUlSTu2/6G+vXtq1Ijhatiosby9fe7XIeQJNt0nvWTJElWoUEHBwcHZ9gkODlb58uW1aNEiW2vDPdSte0+9O+6DDAEtSUWLFdPYd96VJP3661KlpKTYozzYycwZH+nShQsa+MrITAEtSdVq1s523zmffqyTx49q+L/ekbMzI2kPumefH6iXXxmuh1qFqUiRorftP+uLzyRJLwwabA1oSapTt57Ce/dRfPwlLZg/757Vm1fZFNLR0dGqUqXKbftVrVpVhw8ftuUjYEdVq1WXJKUkJ+vihQt2rgb3S3JSkpb/8qM8PDzVrnP3O9r3UNQBfTvnc7Xr0t2hLm8jZ5KSErXp942SpLaPtM+0vW3bdpKkNatW3te68gKbft1NTEyUh4fHbft5eHjo8uXLtnwE7OjYsfSnm7m4uMjH19e+xeC+2b93j65euaJaderLzd1dm9av1dZN65WSnKzA0mX10MPtVLhosUz7paWlacI7o1XAy0sDh4y0Q+Uwu8PR0UpJSVbBQoVUvESJTNur1agpSTqwf9/9Ls30bArpwMBAbd269bb9tm7dKn9/f1s+AnY0e+YXkqQWIaFyc3OciTCO7kj0QUmSX8FCGjXkea2PyHhW8+nHE/XamHFq/UjHDO0Lv/tKkbt3avQ7E+Tt43u/ykUeEhNzUpJUvHjmgJYkT09PeXv76NKlS7p8+bIKFChwP8szNZsud7dp00ZHjhzR5MmTs+3z0Ucf6fDhw7n2wI19+/gN635Ys3qVvv/uW7m4uOiVYa/auxzcRwnxlyRJ69eu0paNv2noqLFavHqzvv9lrcKfeFrJSUl6940Ritq/17rPmdhT+uzjiapTP1htOz5qr9JhclevXJEkubtnfwXWwzN925UrXH29mU0hPWLECHl7e2v48OHq0KGDFi9erMjISEVGRmrx4sXq0KGDhg4dKm9vb40YMeKuCrx48aLKli2revXqafnyv6f75+ITNvE/hw4e1LAhg2UYhka+/i/r2DQcQ1pamiQp9fp1DXhhiB59rI/8ChZScf+SGjT0NbUMe0TXr1/Tt3M+t+4zedxYXUtJ0bDRb9urbOCBZtPl7oCAAC1evFjdunXTL7/8oqVLl2bYbhiGChcurO+//16lS5e+qwLPnz+v0NBQpaSk6L333tOJEyc0YMCAHC9TmpycrOTkv28LiI+Pv6t6HlSnT5/Sk/0e16VLF/XU08/qyQFP27sk3Geenn+vZ9Cuc7dM29t17q41K5Zq5x+bJUkRK5dpfcQq9Xv2RZUuW/6+1Ym8x/N/a2UkJWW/7kDi1fRt+fNzqftmNt8n0bx5cx04cECfffaZVq1apePH029gDwwMVOvWrfX000/Lz8/vrgv09PRURESEVq9erXXr1mncuHFydXVVnz59JP39EI/sjBs3Tm+99dZd1/Egu3jxgvr36a2TJ06oe4/HNOpfb9q7JNhBsRLp80fc3T3kV7BQpu3F/UtKki6cPy9J2rB2tSRp26b12vXHlgx9Dx5IH56a8v5byl/AS4906pZl8MMx+P/ve+f06VNZbr969ari4y/Jx8eH8eh/uKubGf38/DRixIi7vqSdnbS0NBUvXlxFihTRxo0b9cQTTyg+Pl4fffSR4uPjNXDgwNueUY8aNUpDhw61vo6Pj1dgYOA9qTcvunLligb066uoqL/Upm07vTd+Ag9TcVCVqqQPbyQnJyklJVmurhknDcZfSh+z9vD0zNAeuXtntu8Z9b+wrlM/+zUV8OArW66cXF3ddP7cOcWePqVi/5hAtvfPPZKkylWq2qM8U7NpTPp+cXJy0rlz51SqVCnrrVwvvviimjZtquHDh+ubb76x9s1ujNrNzU3e3t4ZvpAuOTlZzz39pHbt3KHmIaGaMm268uXLZ++yYCfFSvirQqWqMgxDO7dtybT9xmXuilWqSZJGv/OB1u08mOVXUL2GktLX7l6386AGvPDy/TsQmI67u4caNW4iSVr6y8+Zti9b9oskqWWrzAvoODpTh7QkFSpUSCdOnJCPj4+2b9+u0NBQffHFF6pbt67Gjh2riRMnShJnf3coNTVVQ14apN83blCDhsGa8Z/P5erqau+yYGe9+z8jSZo++X3FnT1jbY/av1fffTlTktSley+71Ia87cmn0r+3ZkyfqiM3LXK1Y/sf+u6br+Xt7aPuPcPtVZ5pmXrtvhvjzbVq1VLv3r3l6emp8PBwTZ8+XdWrV9f777+v8ePH68yZMxo/fry9y81T5s6ZpeW/pk/48/MrqDf/NSrLfqNGv6mCBQvez9JgR2HtOmnL7+u1bMlC9e3aVjVq11VKcpL+3LVdKSkp6tj1MbV8uJ29y4QJRKxepf/7+CPr62vX0pcQ7tm1k7Vt4IsvK/ShVpKkJs2a64n+T2nu7C/UpUMbNWnWXNdSrmnjhnUyDEPjPviQdbuzYOqQtlgsSktLk8ViUdu2bTVlyhRVqlTJun3YsGHy8/OTu7u7HavMm26ML0qyhnVWXh4yjJB2MK+/PV41g+pq8Q/ztHPbZlksFlWqUl2duvfSI5262rs8mMT58+e0a+eOTO03t50/fy7DttFvjlXVatX01dzZ2rh+nVxcXNW4aTMNfPFlHlWZDZseVXm/DRkyRLt379bq1auVmpp6V+OmPKoSd8IRH1UJ2znSoypxd3L6qErTj0lLUuXKlRUZGamrV68ysQkA4DDyREgXLFhQffr0UWpqqr1LAQDgvsmVy91RUVGKi4tToUKFMowZ55bbLVhyJ7jcjTvB5W7cCS53I6fu+eXu5ORkvf766ypcuLCqVKmiZs2a6f3337du/+qrr1S3bl3t3LnT1o+w4vYqAIAjsimkExMTFRoaqvHjx8vV1VXt2rXLtJjIQw89pF27dmn+/Pm5UigAAI7GppD+4IMPtHnzZg0YMEDR0dFasmRJpj7+/v6qVq2aVq5cmcU7AACA27EppL/77juVKlVKM2bMuOU9ypUrV7Y+eAMAANwZm0L68OHDql+/vpydb70Wiqurqy5cuGBTYQAAODqbQtrDwyNH4Xv48OFceVwlAACOyKaQDgoK0rZt23T27Nls+xw+fFg7duxQgwYNbC4OAABHZlNIP/PMM0pISFCvXr0UFxeXafvFixc1YMAAXbt2Tc8+++xdFwkAgCOy6QEbvXr10pIlSzRv3jyVK1dOTZqkPyd0w4YN6ty5s9auXav4+Hg98cQT6tChQ64WDACAo7B5MZOvv/5a48ePl7u7u5YvXy4pfeWxJUuWyGKx6N1339WsWbNyrVAAABzNXS8Lmpqaqu3bt+vIkSNKS0tTQECAGjRoIFdX19yqMVexLCjuBMuC4k6wLChyKqfLgt7186Tz5cunBg0aMEEMAIBclieeggUAgCOy6Ux6wIABOe5rsVj0xRdf2PIxAAA4NJvGpJ2cbn8CbrFYrI+YNNNzoBmTxp1gTBp3gjFp5NQ9HZNes2ZNlu1paWk6fvy4li9frnnz5umVV15Rx44dbfkIAAAcnk0hHRIScsvtTzzxhNq3b69+/fqpU6dONhUGAICju2cTx3r16qXq1atr7Nix9+ojAAB4oN3T2d0VK1bUtm3b7uVHAADwwLpnIZ2Wlqbdu3fnaJIZAADILNcT9OrVq9q5c6d69eqlqKio245fAwCArNk0cSxfvny37WMYhooUKaIJEybY8hEAADg8m0I6MDBQFosly22urq4qUaKEQkJCNGjQIBUtWvSuCgQAwFHZFNJHjhzJ5TIAAMA/2TQmvXjxYi1dujS3awEAADexKaQfffRRTZ06NbdrAQAAN7EppIsUKSI/P7/crgUAANzEppAODQ3Vli1bZMOzOQAAQA7ZFNLvvPOO4uLi9MorrygpKSm3awIAALJxdve3336rdu3aadq0aZo3b55at26tUqVKyd3dPVNfi8WiN954464LBQDA0eToedLlypVTjx49NH78eEnpz5O+8bzo234Az5NGHsbzpHEneJ40cipXnyd95MgRnT171vp61qxZd18hAAC4JZsud/fr1y+36wAAAP/AI6oAADApQhoAAJPK8eXunTt36u2337bpQ958802b9gMAwJHlaHb3jdncd8owDGZ3I09jdjfuBLO7kVO5OrtbksqXL6+mTZvmSnEAAOD2chzSzZo108yZM+9lLQAA4CZMHAMAwKQIaQAATIqQBgDApAhpAABMKkcTx9LS0u51HQAA4B84kwYAwKQIaQAATIqQBgDApAhpAABMipAGAMCkCGkAAEyKkAYAwKQIaQAATIqQBgDApAhpAABMipAGAMCkCGkAAEyKkAYAwKQIaQAATIqQBgDApHL0POkH0fFzV1UgxWEPHzlU3MfN3iUgD1l/8Jy9S0AeceVyQo76cSYNAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDQCASRHSAACYlLO9C8C9s3PbZg19rs9t+/V/brCeePYlSdJD9Sretn9Q/Uaa9J8v77o+mEvkn7u1cf067dm9S3t27VRs7GlJ0t6Dx7Ld5+LFi/rsk+lauXyZTp86JS8vL9Vv0FDPDRqsqtWq36/ScY8c+Wuv9m7fpMMH/tThA3/qQtwZSdIXy3fm+D0+HPmc9u3YLEma8PWvKlikWIbt+3dt1YRXn8l2/3JVamr0VMf9eUNIP8AKFiqsNh0ezXJbalqaVv7yoySpZp0G1vbs+kvSpvURunTxgmrVqZ+7hcIUZnw8VatXLs9x/7NnYtXnsW46fvyYChcpouYhoYo7e1Yrli/TmtWr9H+fzlTT5i3uYcW415Z8/al2/h5h8/7rl/+ofTs2y2KxyDCMW/Yt6h+oCtWDMreXCLT58x8EhPQDrFTZ8hr51gdZbtu8Ya1W/vKjihYroaD6wdb27PpfTojX6uU/S5Jat+uc+8XC7oLq1FXlKlVVo2Yt1ahVW2EhTZWSkpxt/zGjX9Px48fUPKSlJk+bIU9PT0nSyhW/asig5zRi6GAtX7Ne+QsUuF+HgFxWvlptBZarpDKVqqts5eoa0bedrl9LydG+CRfPa/5/Jql6vcY6feKIzsWeumX/CtWD9NSr7+RG2Q8UQtpB3TiLbvVIJ1ksltv2j1ixVNdSUlStZpACSpW5x9XBHp5+bmCO+56KiVHEmlVydnbWm2+/aw1oSWod1kaPdOiknxcv0sIF36lv/6fuRbm4D9o99qTN+347Y4JSkpPU56XX9eHIZ3OxKsfCxDEHlJh4VRvWrpIkhbXP2VnxyqXpoR7Wrsu9Kgt5yN7IPyVJJQMCVbJkQKbtwcGNJUmrV664r3XBHPZs3aDNa5aqfa+nVdTfsS9X3y3OpB3QutXLlZR4VRUqV1OZcrefKBZ7KkZ7dmyTs7OLQh9udx8qhNklJl6VJHn7+GS53dfPT5K0f//e+1YTzCE5MVFfTX1XJQLL6pGe/XO835mTx/TDF1N1Of6iCvj4qmKNOqpRv6mcnBz7XDJPhXRiYqI8PDwkSYZh5OgyLTK7cak7rH2XHPVftXSxDMNQw6Yt5OPrdw8rQ15RsGBBSVLMyZNZbj9x/Lgk6dLFi7py5Yry589/32qDfS2a+3+Ki43RiA8/l7OLS473O7h3lw7u3ZWhLaBsRQ1880MVK1k6t8vMM/JESE+fPl0LFiyQn5+fChUqpJdeeknVqlWTs3OeKN9Uzp09o+1bf5dTvnxq1aZDjvZZYb3UzYQxpKtZO0iurm46F3dW69ZGqHlIqHWbYRhatPB76+urVy4T0g7iaNQ+rfzvN2oS1lGVa+XsLhCP/F5q26Of6jVrraIlS0mSjh86oIWzP1b0vt2a9NoLGvPJd/LM73UvSzctU19HWLdunWrWrKmpU6eqY8eOKl++vNavX6/Q0FCNGzcuR++RnJys+Pj4DF+ObPWvPyktNVX1g5uqYOEit+3/175IHY0+qAJe3mrc4qH7UCHyAi8vb/V6vK8k6fURQ7Vy+TIlJMTrcPQhDXt5kKIPHbT2tTj45UpHkZaaqtmT35JnAS/1fHZojvcrXaGKejzzispVrakC3j4q4O2jqnUaatSkWapYo67iYmO0ZvH8e1i5uZn2f49hGJoxY4aCgoK0a9cuDR06VBMmTNCOHTvUtm1bjR07Vtu2bbvt+4wbN04+Pj7Wr8BAx57EsOKXOzsrvjFhLKT1I3J1dbtndSHveWX4SD3ctp3OnYvT4IHPKrhODbV/uKVWrViuUf8aa+3n7eVtvyJx36z479c6dnC/uj89RF4+dz8s5pQvnx55rL8kKfKPjXf9fnmVaa8Xb9y4UfPmzdPmzZvl7u5uvRHe3d1dw4YN044dO/T2229r8eLFt3yfUaNGaejQv3+ri4+Pd9igPnr4oA4e2CsPz/xqGhp22/6pqala8+uNe6M73evykMe4urlpysefaNvWzVr/21pdOH9OxUv465EOnWRR+nyRUqXLyNWNX+4cwa5Na2WxWLRxxRL9vnJJhm2Xzp+TJM3496tycXHRI48NUM0GTW/7njfGoi+ej8v9gvMI04b0li1b5O3trUKFClnbbkwUq169unr06KFx48YpLi5OhQsXzvZ93Nzc5MYPCUnSip/Tz4qbt3xY7v+bgHcr27ds1Lm4MypWoqRq3bQqGXCz+g2CVb9BcIa2H/+7QJLUMLiRPUqCnRiGob/2/JHt9uh9uyVJTR7O2S/9VxPShyfd3G//8+pBZdqQ9vT0VEpKis6ePaty5cpZA9owDLm7u6tSpUpyd3fXpk2b1KFDziZAOTLDMLRqWfpvtzm/Nzr9KkXrdjlb8ASQ0r/XvvlqriSp+2O97VwN7pcRH36R/ba+j+hc7Kks1+6+lT/Wr5Qkla5Q9a7ry6tMOyYdFhYmwzAUERGhlJT0ZehuXvs1ICBAV69eVY0aNexVYp6ye8dWxZ46qcJFi6lOg8a37Z+UmKj1a9IXomABE2QlJuakzp3LeBkyKSlJY0aP1J5dO9WlWw/Vqh1kn+KQZ6xY+JXOnzmdoc0wDEX8tEArFn4ti8Wi0A497FSd/Zn2TDogIECdO3fWjBkzFBISokaNGlnP5lJSUvTFF1+oXr161vs1cWsrf0k/K27VtmOOFgfYELFCiVevqHL1WipVpty9Lg8msHbNKs34eKr19bX/rdEc3u3vKy8vvDhYIS1bSZI2/75RY0aPVPUatVTC31/JSUnavn2bLl28qGbNQzTm7Xfv7wEg1+3a/Jt++voz6+vU69ckSe8O7mtt6/D4M6odbPuDVFb892vN/3SySlesosLFS+paSopOHI5S3OmTsjg5qdfAkSpTqZrtB5HHmTakXV1d9d5776lOnTp6+umnNWPGDFWsWFGenp76z3/+ox07dmjcuHHy9mbm6O2kpCTrt1XLJOX84Rgr/nepO+wRJow5ivPnz2v3rh2Z2m9uO3/+vPXP1WvU1MNt22nXzh3avy9Srq5uqli5sh7t1lNdu/dkiOQBkHDpgqL378nUfnNbwqULd/UZbbo9ocg/ftfJo4cUczRaqanX5VOwsBq1aq/WXXqpbGXHvlpqMW73/DA7W7JkiSZPnqx169apTp06iomJkYeHh95//31169btjt8vPj5ePj4+2vbXKRXg1hDcRnEfJh0i536PPn/7ToCkK5cT1L1ReV26dOmWJ5umPZO+oWPHjmrTpo2ioqK0Z88elSxZUs2bN7d3WQAA3HOmD2kp/dJ39erVVb16dXuXAgDAfWPa2d0AADg6QhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAAJMipAEAMClCGgAAkyKkAQAwKWd7F3C/GYYhSbp8OcHOlSAviLe42bsE5CFX+LmCHLp6Jf175UYmZcfhQjohIf0vJrRuJTtXAgBwdAkJCfLx8cl2u8W4XYw/YNLS0hQTEyMvLy9ZLBZ7l2Ma8fHxCgwM1PHjx+Xt7W3vcmBifK/gTvD9kjXDMJSQkCB/f385OWU/8uxwZ9JOTk4KCAiwdxmm5e3tzX8k5AjfK7gTfL9kdqsz6BuYOAYAgEkR0gAAmBQhDUmSm5ubxowZIzc3ZjPj1vhewZ3g++XuONzEMQAA8grOpAEAMClCGgAAkyKkAQAwKUIaAACTIqQBADApQhoAcM9wA9HdIaQd3NGjR/lPhBxLS0uzdwnIIxITE5WcnKzjx48rKSnJ3uXkWYS0A0tOTlZ4eLjKlStHUCNb+/fv1+jRo3X06FEeSoMc2bdvn/r06aP69eurfPnyaty4sV577TV7l5UnsZiJAzMMQxs2bNALL7wgFxcX/fHHH/wQRgbXrl1T06ZNtW3bNlWoUEGdO3dWw4YN1aNHD2uf1NRU5cuXz45Vwkz27Nmj5s2bq0+fPqpTp44KFiyoOXPmaNmyZQoLC9PChQvl4uJi7zLzDELawaWlpWnLli168skn5eHhQVAjkwkTJsjZ2Vk1atTQhg0bNHXqVLVv315NmjTR888/b/1+MQyD7x0Hd/bsWbVp00Zt2rTRuHHjMrTPnz9fI0eOVIcOHTRv3jw7Vpm3cLnbwZw+fVqbNm2yvnZyclK9evU0Z84cXb58WfXq1ePSNzJo0KCBxo4dKz8/P40dO1aRkZGqUKGChg8friZNmuizzz7TX3/9RUBDJ06c0LVr1/T4448rNTVVUvqJQJEiRdSnTx+NGjVKS5Ys0aJFi+xbaB5CSDuQ48ePq0aNGmrSpIlatmyp119/XatXr1ZiYqIaNmyor7/+WpIUFBREUMMqNDRUzz77rKZMmaKkpCSVKFFC+/btU6lSpVS5cmV99dVXqlGjhiZNmmTvUmFnu3bt0sGDB1WjRg3ly5dPhmHIySk9Znx8fNS7d2+5uLjo4MGDdq407yCkHUhaWpoCAwNVqVIlXb58WTExMWrfvr1CQkL0xBNP6PDhwxo1apSSk5PVqlUrghpWwcHBio6Olqurq55++mlFRERowYIFmj17tj799FN9+OGHatOmjb3LhJ1VqFBBkvTDDz9IUqarK2XLllW5cuV08uTJ+15bXkVIO5DSpUvr+++/V7Vq1VSyZEm98MILOnDggEaOHKno6GhNnDhR/fv3l6urqyIiItStWzd7lwyT6N69u1xcXOTi4qKlS5fq119/VfXq1SVJlStX1uDBg62v4bjKlCkjb29vzZ07V0ePHrW237h178KFC/Lw8FC9evXsVWKeQ0g7mAoVKmjcuHFKSkrSG2+8odjYWIWHh2v9+vX69ddf9cknn6hjx44KCgrSG2+8Ye9yYQI3rqiMHDlSFSpU0PTp01W7dm2utCCTgIAAzZgxQ8uWLdMbb7yhyMhISbJe8p40aZJiYmLUvHlze5aZpzC720FFRUXppZdekiSNGjVKISEhGbZfv35dzs7O9igNJhUbG6tmzZopPDxc77zzjr3LgUmlpqbq888/14svvqjy5curadOmKlGihA4fPqylS5dq1apVqlOnjr3LzDMIaQcWFRWlwYMHyzAMvfnmm2rSpIm9S4LJffXVV3r++ee1evVqNWzY0N7lwMQ2b96sDz74QAcOHJCvr69q166tl156SVWqVLF3aXkKIe3goqKiNHToUMXFxWny5Mlq1KiRvUuCiZ08eVJ9+vTRl19+qYCAAHuXA5NLTU2Vk5OTLBaL0tLSrJe9kXOENLR//3698cYbmjhxokqVKmXvcmBySUlJcnd3t3cZyANuXuCGxW5sQ0hDkpSSkiJXV1d7lwEAuAkhDQCASTFAAACASRHSAACYFCENAIBJEdIAAJgUIQ0AgEkR0gAAmBQhDSj9kXo3fzk5OcnX11fNmzfX559/bveHScyePVsWi0Vjx47N0N6/f39ZLBZFRETYpS5bhYaGymKx6MiRI/fk/cuUKcPCGXggENLATfr166d+/frp8ccfV7Vq1bRhwwY988wz6t27t71Lu2ey+wUAgP3xmCPgJrNnz87wesWKFWrXrp3mzZunxx9/XB06dLBPYdkYN26cXnvtNZZzBR5QnEkDtxAWFqa+fftKkhYtWmTfYrJQokQJValSRZ6envYuBcA9QEgDt3Hj2bfHjx+3tlksFpUpU0YpKSl6++23VaVKFbm5ualLly7WPlevXtW4ceNUp04dFShQQAUKFFCjRo00Z86cbD9rw4YNat26tby8vOTr66s2bdpo8+bN2fa/1Zj0lStXNH78eNWvX1/e3t7Knz+/qlSpokGDBumvv/6SlD42/OSTT0qS3nrrrQzj8v+8qrBv3z71799fgYGBcnNzU7FixRQeHq7IyMgsa0tNTdWHH36oKlWqyN3dXYGBgXr55ZcVHx+f7fHczrJly9SpUycVK1ZMbm5uCgwMVIcOHfTDDz/kaP+ff/5ZAwYMUNWqVa1/J7Vr19Z7772n5OTkLPf55ZdfFBYWppIlS8rNzU3+/v5q1qyZ3nrrrQz9DMPQ119/rWbNmqlYsWLWY27durWmT59u8zHDsXG5G7iNhIQESZKbm1uG9rS0NHXp0kW//fabQkJCVKtWLRUqVEiSdObMGYWFhWn37t0qXry4QkJCZBiGNm7cqP79+2vbtm2aNm1ahvf76aef9Oijj+r69etq2LChypUrp127dqlFixbq37//HdV86tQphYWFKTIyUn5+fgoNDZWbm5uio6P1ySefqGLFiqpUqZLatm2r69eva8OGDapdu7aCgoKs71GhQgXrnxctWqTw8HAlJycrKChIjRo10vHjxzV//nwtWbJES5cuVYsWLTLU0KdPH82bN0+enp56+OGH5ezsrDlz5mjDhg1ycXG5o+ORpGHDhmnSpElycnJS48aNVapUKcXExGjDhg06ceKEunXrdtv3eOqpp5SYmKgaNWqoVq1aunTpkrZs2aLRo0dr1apVWr58ufLly2ftP336dL344ovKly+fmjZtqpCQEMXFxWnfvn0aO3asxowZY+07YsQIffjhh3Jzc1OLFi1UuHBhnT59Wrt379bBgwc1aNCgOz5mQAYAQ5KR1X+HtLQ0o3HjxoYkY/To0Zn6V6hQwThx4kSm/dq1a2dIMl5++WUjKSnJ2n769Gmjfv36hiRj6dKl1vb4+HijSJEihiRj5syZGT5/5MiR1s8bM2ZMhs/p16+fIclYs2ZNhvZWrVoZkoyePXsaCQkJGbYdPnzY2LVrl/X1rFmzsnzvm/vnz5/fKFCggLFixYoM25YuXWq4uLgYgYGBRnJysrV93rx5hiSjVKlSxuHDh63tsbGxRo0aNazHc/O2W/nyyy8NSYa/v7+xY8eODNuuXr1qLF++PENb6dKls/z3XLRokXH16tUMbfHx8UaHDh0MScacOXMybCtVqpRhsViMrVu3ZmhPS0vL8HeemJhouLm5GV5eXkZ0dHSGvteuXTN+++23HB0n8E+ENGBkDunr168bf/31l9G/f39DkuHm5mYcPHgwU//vv/8+03vt2LHDkGQ0aNDASE1NzbR9+/bthiSjU6dO1raZM2cakowWLVpk6p+SkmIEBATkOKQ3b95sSDKKFi1qxMfH3/bYbxfSL7/8siHJmDZtWpbbBw8ebEgyFi5caG1r0aJFpl84bli6dOkdh3TVqlUNSca8efNy1D+7kM5OVFSUIcno2rVrhnYPDw/Dz8/vtvvHxsYakoygoKAcfyaQE4xJAze5MR7r7OysSpUqafbs2fLy8tK3336r8uXLZ+rbsWPHTO+xfPlySVKXLl3k5JT5v9iNMeotW7ZY29atWydJCg8Pz9TfxcVF3bt3z/ExrFy5UpLUq1cveXl55Xi/7Nw4nq5du2a5vXnz5pJkPZ5r165p06ZNkqTHHnssU/+2bdvKz88vx58fExOjffv2ydfXVz179ryj2rMSFRWljz76SC+99JIGDBig/v3765133rFuu1m9evV04cIFPfXUU9mOvUtS0aJFFRAQoJ07d+q1115TdHT0XdcJSIxJAxn069dPkuTk5CRvb2/VrFlTXbt2zTJUihYtmmmcWpJ1gY7Ro0dr9OjR2X5WUlKS9c8xMTGSpNKlS2fZt0yZMjk9BOsEt3/+UmGrG8dTsmTJW/aLi4uTJJ07d04pKSkqUqRItrPOS5curQsXLuTo828cT7ly5e5qgRLDMDR8+HBNnjw528Vpbsw/uGH69Onq0qWLZs6cqZkzZ6pYsWIKCQlR165d1b179wzj13PmzFF4eLjGjx+v8ePHq3Tp0goJCVF4eLgeeeQRm+uGYyOkgZv8c0bzrbi7u2fZnpaWJklq1qxZrgWlPd04nhu/wGQnODj4fpRjs++++06TJk1SYGCgJk+erMaNG6tIkSJycXFRSkqK3NzcMoV3rVq1tHfvXi1btky//PKLIiIiNH/+fM2fP1+NGzdWRESEXF1dJUkPPfSQDh48qJ9++knLli1TRESE5s6dq7lz56pbt25asGCBPQ4beRwhDeSygIAASemXu4cNG5ajfUqUKCFJOnr0aJbbs2vPSmBgoCTp0KFDOd7nVgICAnTo0CFNnDjROnv9VgoVKiRXV1edPXtWiYmJ8vDwyNTn2LFjOf78G8cTHR0twzBsPpv+73//K0maMWOG2rdvn2HbrS5Pu7u7q0uXLtbb6yIjI9W7d2/9/vvv+vzzzzVw4EBrX29vb/Xu3du6Qt2mTZvUo0cP/fDDD/rll1/Url07m2qH42JMGshlYWFhkv4OhZy4Ma47f/78TNuuX7+e4/uAJal169aSpG+//VaXL1++bf8bZ4LXr1/PcvudHo+Li4v1rDqr41m+fLnOnz+fo/eSJH9/f1WtWlUXL17U999/n+P9/unG5fUbv0TdLKs6s1O9enXr7VR//vnnLfs2atTIuhjO7foCWSGkgVwWHByssLAwbdiwQYMGDcpy8Y5du3Zp2bJl1tc9evRQoUKFFBERkWGxE8MwNGbMmDs682zYsKFatmypM2fO6Nlnn9WVK1cybD9y5Ij27Nljfe3v7y9JOnDgQJbvN2zYMHl4eGj48OFauHBhpu3JyclasGCBTpw4YW174YUXJClT7XFxcXr11VdzfCw3vPbaa5KkoUOHavfu3Rm2JSUlacWKFbd9j0qVKkmSPv300wyXtdetW6cJEyZk6n/16lVNnTpVFy9ezNCelpZm/be7cZZ/7NgxzZ49W1evXs1U25o1azL0Be6IPaeWA2ahbO6TvlX/0qVLZ7s9NjbWqFOnjiHJ8PX1NUJDQ43evXsb7du3NwIDA633UN9s0aJFRr58+QxJRnBwsNGrVy+jWrVqhouLi/HMM8/c0X3SJ06cMCpXrmxIMgoWLGh06tTJ6NGjh1G3bl3DycnJmDx5srVvYmKiUbRoUUOSERISYjz55JPGU089ZWzYsCFDbZ6entZ7wzt27GiEh4cbzZs3N/Lnz29IynT/co8ePQxJRv78+Y1OnToZXbt2NXx9fY26desajRo1uqNbsAzDMF566SVDkpEvXz6jWbNmRq9evYzQ0FDD19fXqF27doa+Wd2CdeDAAWut1apVs9ZvsViM4cOHZ/o3vXDhgiHJcHFxMRo1amSEh4cbXbt2tf77lSlTxoiLizMM4+/b7jw9PY0WLVoYvXv3Njp37my9971+/foZ7pcHcoqQBozcD2nDSA+/qVOnGk2aNDF8fHwMV1dXIzAw0AgJCTEmTJhgHD9+PNM+v/32m9GyZUsjf/78hre3t9GqVStj48aN2d7LnF1IG0b6Ih1vv/22UatWLcPDw8MoUKCAUaVKFePFF180oqKiMvTdunWrERYWZvj4+BgWi8WQZMyaNStDn4MHDxoDBw40KlasaLi7uxteXl5G5cqVjfDwcGP+/PkZFjMxjPRFPMaPH29UqlTJcHV1Nfz9/Y2BAwcaFy9eNEJCQu44pA3DMH788UejTZs2RsGCBQ1XV1cjICDA6NChQ4Z7tA0j+/uk9+3bZ3Ts2NEoWrSo4enpadSpU8f49NNPDcPI/G967do1Y/r06UbXrl2N8uXLG56enoavr69Rq1Yt46233jLOnTuX4e964sSJRrt27YwyZcoY7u7uRqFChYz69esbkydPNq5cuXJHxwncYDEMOz8oFwAAZIkxaQAATIqQBgDApAhpAABMipAGAMCkCGkAAEyKkAYAwKQIaQAATIqQBgDApAhpAABMipAGAMCkCGkAAEyKkAYAwKT+H8r0r4tn2iqtAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "fig, ax = model.test_cm.plot(model.test_cm_log, cmap=\"Blues\", labels=dm.test_set.classes)\n",
    "plt.show()\n",
    "wandb.log({\"test_cm\": fig})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/g113056077/.pyenv/versions/ecg-fl/lib/python3.11/site-packages/wandb/sdk/lib/ipython.py:84: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython.display\n",
      "  from IPython.core.display import HTML, display  # type: ignore\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "    <style>\n",
       "        .wandb-row {\n",
       "            display: flex;\n",
       "            flex-direction: row;\n",
       "            flex-wrap: wrap;\n",
       "            justify-content: flex-start;\n",
       "            width: 100%;\n",
       "        }\n",
       "        .wandb-col {\n",
       "            display: flex;\n",
       "            flex-direction: column;\n",
       "            flex-basis: 100%;\n",
       "            flex: 1;\n",
       "            padding: 10px;\n",
       "        }\n",
       "    </style>\n",
       "<div class=\"wandb-row\"><div class=\"wandb-col\"><h3>Run history:</h3><br/><table class=\"wandb\"><tr><td>learning_rate</td><td>███████▃▃▃▃▃▃▃▃▁▁▁▁▁</td></tr><tr><td>test_acc</td><td>▁</td></tr><tr><td>test_f1</td><td>▁</td></tr><tr><td>test_loss</td><td>▁</td></tr><tr><td>train_acc</td><td>▁▃▇▇▇▇▇██████████████</td></tr><tr><td>train_f1</td><td>▁▃▇▇▇▇▇██████████████</td></tr><tr><td>train_loss</td><td>█▆▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁</td></tr><tr><td>valid_acc</td><td>▁▃▇██████████████████</td></tr><tr><td>valid_f1</td><td>▁▃▇██████████████████</td></tr><tr><td>valid_loss</td><td>█▆▃▂▂▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▂</td></tr></table><br/></div><div class=\"wandb-col\"><h3>Run summary:</h3><br/><table class=\"wandb\"><tr><td>learning_rate</td><td>0.00025</td></tr><tr><td>test_acc</td><td>0.80015</td></tr><tr><td>test_f1</td><td>0.79826</td></tr><tr><td>test_loss</td><td>0.62078</td></tr><tr><td>train_acc</td><td>0.88575</td></tr><tr><td>train_f1</td><td>0.88182</td></tr><tr><td>train_loss</td><td>0.3066</td></tr><tr><td>valid_acc</td><td>0.81832</td></tr><tr><td>valid_f1</td><td>0.81347</td></tr><tr><td>valid_loss</td><td>0.49544</td></tr></table><br/></div></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View run <strong style=\"color:#cdcd00\">ecg-federated</strong> at: <a href='https://wandb.ai/devilhyt/ecg-federated/runs/d6zpnl4h' target=\"_blank\">https://wandb.ai/devilhyt/ecg-federated/runs/d6zpnl4h</a><br/> View project at: <a href='https://wandb.ai/devilhyt/ecg-federated' target=\"_blank\">https://wandb.ai/devilhyt/ecg-federated</a><br/>Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Find logs at: <code>wandb_logs/wandb/run-20241130_045536-d6zpnl4h/logs</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "wandb.finish()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ecg-fl",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
